### ISSUE TITLE
Null-safe support

### ISSUE THREAD

**Issue by TitanKing** [JaffaKetchup/flutter_map_tile_caching#1]
Thanks for the great work with this plugin. Is a null-safe version in the near future plans or should I just go ahead an convert it? I assume we are waiting for a official null safe flutter_map package first.

**Comment by JaffaKetchup** [comment]
Hi,
Yes, I am waiting for all dependencies (flutter_map) to become null safe before migration, and I'll try to migrate as soon as possible after this.
Whilst you're waiting, it would help to give a star on GitHub and a like on pub.dev!
Thanks, 
Luka S.

**Comment by JaffaKetchup** [comment]
It looks like flutter_map null safety will be released soon. Once that's published on pub.dev, I'll try to migrate this within 24 hours (48 max). Looking forward to it!

**Comment by JaffaKetchup** [comment]
For all further information, please see https://github.com/JaffaKetchup/flutter_map_tile_caching/pull/2 PR.
