### ISSUE TITLE
Disable ISAR inpector.

### ISSUE THREAD

**Issue by Mmisiek** [JaffaKetchup/flutter_map_tile_caching#100]
### What do you want implemented?

An option to disable Isar inspector when initializing cache. 
Isar inspector shows only one schema (first). I am using it in my project and it prevents me from seeing my schema as only one at the time is supported.

### What other alternatives are available?

None

### Platforms Affected

Android, iOS, Windows

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] I have checked for similar feature requests which may be duplicates
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map_tile_caching) of this package
- [X] If I am using FMTC in a proprietary project, I have read and understood [this important legal notice](https://fmtc.jaffaketchup.dev/#proprietary-licensing)

**Comment by JaffaKetchup** [comment]
Hey @Mmisiek, I think v7.1.1 contains the features you want? Check https://pub.dev/documentation/flutter_map_tile_caching/latest/flutter_map_tile_caching/FlutterMapTileCaching/debugMode.html.

**Comment by Mmisiek** [comment]
Yes, that's exactly what I needed, thanks. I was using `^7.0.0` and somehow it was not upgraded automatically. Thanks for great plugin.

**Comment by JaffaKetchup** [comment]
Great!
