### ISSUE TITLE
Isar inspector stuck "loading"

### ISSUE THREAD

**Issue by Mmisiek** [JaffaKetchup/flutter_map_tile_caching#101]
### What is the bug?

I am trying to see Isar schema content but inspector shows no content and is stuck on "loading".
<img width="965" alt="image" src="https://user-images.githubusercontent.com/4585329/219849029-43bc3e11-d0f2-42a5-80f3-6a95cd1b56e5.png">

### What is the expected behaviour?

See schema content ?

### Platforms Affected

Android

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] I have checked for known issues in the GitHub tracker and [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#known-issues)
- [X] I have completed the pre-report checks listed [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#reporting-a-bug)
- [X] If I am using FMTC in a proprietary project, I have read and understood [this important legal notice](https://fmtc.jaffaketchup.dev/#proprietary-licensing)

**Comment by JaffaKetchup** [comment]
Hey @Mmisiek,
This is out of my control. If you use the button in the bottom left you can switch stores. Usually Isar shows 'loading...' for schemas not used in the current store.

**Comment by Mmisiek** [comment]
So I see few stored, default, .recovery and some with numbers. Which one would be correct ?

**Comment by Mmisiek** [comment]
Default :)

**Comment by JaffaKetchup** [comment]
Hey @Mmisiek,
'default' is the name Isar gives to unnamed instances. I'd recommend giving it a name.
'.recovery' is an FMTC database used for handling the bulk download recovery system.
The numbers stores are FMTC databases where the numbers are a hash of the store name.
