### ISSUE TITLE
[BUG] Repeating download raises exception

### ISSUE THREAD

**Issue by Mmisiek** [JaffaKetchup/flutter_map_tile_caching#103]
### What is the bug?

I repeated (on button press) cache download and got the exception:
`/flutter (23312): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_progressManagement@1508177007' has not been initialized.
E/flutter (23312): #0      DownloadManagement._progressManagement (package:flutter_map_tile_caching/src/store/download.dart)
download.dart:1
E/flutter (23312): #1      DownloadManagement.cancel
download.dart:128
E/flutter (23312): <asynchronous suspension>
E/flutter (23312):
I/flutter (23312): Total markers:0
I/flutter (23312): Total paths:1`

### What is the expected behaviour?

No exception.

### How can we reproduce this issue?

My code:
```
       if (globals.connected) {
            await DialogsFactory()
                .confirmationDialog(context, "Offline maps",
                    "Do you want to download maps and data for selected view for offline use ? The operation might take some time.")
                .then((download) async {
              if (download!) {
                int successfulTiles = 0;
                int tiles = 0;
                // define region
                TileLayer streetMapOptions = TileLayer(
                  minZoom: globals.minOfflineZoom,
                  maxZoom: globals.maxOfflineZoom,
                  urlTemplate: "https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}",
                  additionalOptions: {
                    'accessToken':
                        'XXXX',
                    'id': _mapStyle,
                  },
                );

                TileLayer satMapOptions = TileLayer(
                  minZoom: globals.minOfflineZoom,
                  maxZoom: globals.maxOfflineZoom,
                  urlTemplate:
                      "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}.jpg",
                );

                // define region
                final region = RectangleRegion(_bounds);
                final downloadableStreet = region.toDownloadable(
                    globals.minOfflineZoom.toInt(), globals.maxOfflineZoom.toInt(), streetMapOptions,
                    parallelThreads: 20, preventRedownload: true, seaTileRemoval: true);
                final downloadableSat = region.toDownloadable(
                    globals.minOfflineZoom.toInt(), globals.maxOfflineZoom.toInt(), satMapOptions,
                    parallelThreads: 20, preventRedownload: true, seaTileRemoval: true);
                // download manager
                _managerStreet = FlutterMapTileCaching.instance(globals.streetMapCacheStoreName).download;
                _managerSat = FlutterMapTileCaching.instance(globals.satMapCacheStoreName).download;
                tiles = await _managerStreet.check(downloadableStreet) + await _managerSat.check(downloadableSat);
                if (kDebugMode) {
                  print("Tiles to download $tiles\n");
                }
                setState(() {
                  _isDownloading = true;
                  _progressValue = 0;
                  _dowloadMessage = "Dowloading map tiles 0/$tiles";
                });
                final broadcastStream = FMTC
                    .instance(globals.satMapCacheStoreName)
                    .download
                    .startForeground(region: downloadableSat, bufferMode: DownloadBufferMode.tiles)
                    .asBroadcastStream();

                await broadcastStream.listen((event) {
                  Future.delayed(Duration(milliseconds: 50)).then((onValue) {
                    setState(() {
                      _progressValue = successfulTiles / tiles;
                      successfulTiles = event.successfulTiles;
                      _progressKey = Object();
                      _dowloadMessage = "Dowloading map tiles  $successfulTiles/$tiles";
                      // check if not canceled
                      if (!_isDownloading) {
                        _managerSat.cancel();
                        return;
                      }
                    });
                  });
                }, onDone: () {
                  if (!_isDownloading) {
                    return;
                  }
                  setState(() {
                    _progressValue = (successfulTiles) / tiles;
                    ;
                    _dowloadMessage = "Dowloading map tiles $successfulTiles/$tiles";
                  });

                  final broadcastStream = FMTC
                      .instance(globals.streetMapCacheStoreName)
                      .download
                      .startForeground(region: downloadableStreet, bufferMode: DownloadBufferMode.tiles)
                      .asBroadcastStream();
                  broadcastStream.listen((event) {
                    Future.delayed(Duration(milliseconds: 100)).then((onValue) {
                      setState(() {
                        _progressValue = (successfulTiles + event.successfulTiles) / tiles;
                        _progressKey = Object();
                        _dowloadMessage = "Dowloading map tiles  ${(successfulTiles + event.successfulTiles)}/$tiles";
                        if (!_isDownloading) {
                          _managerStreet.cancel();
                          return;
                        }
                      });
                    });
                  }).onDone(() async {
                    await cacheFieldsInView(_bounds).then((value) {
                      setState(() {
                        _isDownloading = false;
                      });
                    });
                  });
                });
              } // if download
            });
          } else {
            await DialogsFactory().infoDialog(context, "No connection",
                "Looks like there is no Internet connection necessary to download maps and data.");
          }
```

### Do you have a potential solution?

Ignore exception.

### Platforms Affected

Android

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] I have checked for known issues in the GitHub tracker and [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#known-issues)
- [X] I have completed the pre-report checks listed [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#reporting-a-bug)
- [X] If I am using FMTC in a proprietary project, I have read and understood [this important legal notice](https://fmtc.jaffaketchup.dev/#proprietary-licensing)

**Comment by JaffaKetchup** [comment]
Hey @Mmisiek, and thanks for the report :)
Can you check the 'v7.1.3' branch please, I think it should fix this issue. To depend on a GitHub repository branch, please see https://fmtc.jaffaketchup.dev/get-started/installation#from-github.com, and `ref: v7.1.3` below the `url` field.

**Comment by Mmisiek** [comment]
> Hey @Mmisiek, and thanks for the report :) Can you check the 'v7.1.3' branch please, I think it should fix this issue. To depend on a GitHub repository branch, please see https://fmtc.jaffaketchup.dev/get-started/installation#from-github.com, and `ref: v7.1.3` below the `url` field.

I will try, sure. Can you also  check how to avoid exception when tile in cache is not found and there is no network. It is unhandled exception and makes my debugging difficult.

**Comment by Mmisiek** [comment]
> Hey @Mmisiek, and thanks for the report :) Can you check the 'v7.1.3' branch please, I think it should fix this issue. To depend on a GitHub repository branch, please see https://fmtc.jaffaketchup.dev/get-started/installation#from-github.com, and `ref: v7.1.3` below the `url` field.

Seems to be working :) no exception anymore.

**Comment by JaffaKetchup** [comment]
Unfortunatley that point has been raised before, but there's nothing I can do about it as far as I know.
It simply represents a fall through case: I can't return any bytes, so an error has to be thrown somewhere. As far as I can see, `flutter_cached_network_image` does the same (although untested by me):
![image](https://user-images.githubusercontent.com/58115698/219978699-e0fed43b-859d-45d4-b893-e68fab099d03.png)

You might be able to ignore a specific type of issue in your IDE? I always test with the 'Run Without Debugging' tool in VSCode, which only outputs errors to the console (instead of pausing execution) - but I can see this is not ideal in some cases.

**Comment by JaffaKetchup** [comment]
Great, glad to hear it's fixed. I'll try to release a new version tomorrow - although I've been releasing a lot of versions recently!

**Comment by Mmisiek** [comment]
> Great, glad to hear it's fixed. I'll try to release a new version tomorrow - although I've been releasing a lot of versions recently!

I'm releasing up to 10 versions per day of my app for Alpha testers ;) so do not worry.

**Comment by Mmisiek** [comment]
> Unfortunatley that point has been raised before, but there's nothing I can do about it as far as I know. It simply represents a fall through case: I can't return any bytes, so an error has to be thrown somewhere. As far as I can see, `flutter_cached_network_image` does the same (although untested by me): ![image](https://user-images.githubusercontent.com/58115698/219978699-e0fed43b-859d-45d4-b893-e68fab099d03.png)
> 
> You might be able to ignore a specific type of issue in your IDE? I always test with the 'Run Without Debugging' tool in VSCode, which only outputs errors to the console (instead of pausing execution) - but I can see this is not ideal in some cases.

Basically, I can ignore it in development and production. It is just a little annoying in testing. I am wondering if I can catch t somehow.

**Comment by JaffaKetchup** [comment]
Unfortunately you can't prevent it AFAIK.
I've added methods to catch it (`errorHandler`), but the same still stands (as seen in the screenshot): no bytes to return = only escape route is an error.
You could throw an error in the callback, and that would stop the FMTC error, but that defeats the point.

**Comment by Mmisiek** [comment]
Maybe we can ask Dart people to find a solution. They are pretty responsive,

**Comment by JaffaKetchup** [comment]
(I also am not a fan of doing this, especially as you've donated, but please do note the GPL 3 license applied to this project, if you're using this for a proprietary application. Please see the README or docs site for more info, and feel free to get in touch. If your app is proprietary, I'm sure we can work something out :))

**Comment by JaffaKetchup** [comment]
Just keeping this open for now, until I release a new version.
I think this is a limitation of the core of the language. Something must be returned from a method that expects a return value: nothing can be done about that. Potentially the necessary methods return types could be made nullable, but there might be a reason they aren't already.

**Comment by JaffaKetchup** [comment]
@Mmisiek Please don't be 'scared off' asking more questions in the future, I'm always happy to help. Many thanks for all your bug reports so far :)
If you are developing a proprietary application, please do get in touch, I prefer to set a price that works for both of us. If your app is non-profit but proprietary, please get in touch, and I'll be happy to offer a free license.

**Comment by Mmisiek** [comment]
Will do.
