### ISSUE TITLE
[BUG] `initialise` can cause invalid integer parsing errors

### ISSUE THREAD

**Issue by sikandernoori** [JaffaKetchup/flutter_map_tile_caching#106]
### What is the bug?

On app Launch when I initialize FMTC I get bellow error.

```
Restarted application in 472ms.
flutter: ╔══════════════════════════════════════════════════════════╗
flutter: ║                   ISAR CONNECT STARTED                   ║
flutter: ╟──────────────────────────────────────────────────────────╢
flutter: ║           Open the link to connect to the Isar           ║
flutter: ║          Inspector while this build is running.          ║
flutter: ╟──────────────────────────────────────────────────────────╢
flutter: ║ https://inspect.isar.dev/3.0.6-dev.0/#/55467/hTBTxgvcX80 ║
flutter: ╚══════════════════════════════════════════════════════════╝
[FlutterMapTileCaching.error] FormatException: Invalid radix-10 number (at character 8)
                              -8813321830148695224.isar
```

### What is the expected behaviour?

FMTC should initialized.

### How can we reproduce this issue?

```
  void main() async {
    WidgetsFlutterBinding.ensureInitialized();

    await FlutterMapTileCaching.initialise(
      errorHandler: (error) => info(error, "FlutterMapTileCaching.error"),
      debugMode: true,
    );
...
```

### Do you have a potential solution?

No.

### Platforms Affected

iOS

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] I have checked for known issues in the GitHub tracker and [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#known-issues)
- [X] I have completed the pre-report checks listed [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#reporting-a-bug)
- [X] If I am using FMTC in a proprietary project, I have read and understood [this important legal notice](https://fmtc.jaffaketchup.dev/#proprietary-licensing)

**Comment by JaffaKetchup** [comment]
Hi @sikandernoori,

Can you please say what the store names you are trying to use are? 

This error is very confusing, as it's not what I'd expect. `-8813321830148695224` is a valid number. '-8813321830148695224.isar' is not, but I'm not sure why '.isar' is there:
```dart
final id = path.basenameWithoutExtension(f.path);
```

Many thanks for the report!

**Comment by sikandernoori** [comment]
@JaffaKetchup 

store name = "mainCache"

The reason .isar is present because I believe on every reload you are creating copy of db with extension appended.

Not sure if that is expected behavior. I will share screenshot next I work on it.

**Comment by sikandernoori** [comment]
https://github.com/JaffaKetchup/flutter_map_tile_caching/pull/107/files#diff-fa8eaee168f8dc3d74c3072badefd43924529ecbdffc84f2c1ee75ce72c0dde4R85

the actual problem is in the way you are filtering isar database, in fmtc directory there are `.isar` files and `.isar.lock` files

So filter should be like below

```
        await directory
            .list()
            .where(
              (e) =>
                  e is File &&
                  !path.basename(e.path).startsWith('.') &&
            path.basename(e.path).endsWith('.isar'),
                  ```

**Comment by JaffaKetchup** [comment]
@sikandernoori Lock files should already be taken care of. See https://github.com/JaffaKetchup/flutter_map_tile_caching/blob/2db3bfdcae9e22afa8ebec49c67506109d07de61/lib/src/db/registry.dart#L57. They are deleted on every launch, before this block of code.

**Comment by JaffaKetchup** [comment]
@sikandernoori I will implement a similar fix in v7.1.0 to #107, but it won't be exactly the same. I am concerned about side effects however.

**Comment by JaffaKetchup** [comment]
Fixed in 5617ca8.

**Comment by sikandernoori** [comment]
> @sikandernoori Lock files _should_ already be taken care of before this block. See this line, where these files are filtered out and deleted:
> 
> https://github.com/JaffaKetchup/flutter_map_tile_caching/blob/2db3bfdcae9e22afa8ebec49c67506109d07de61/lib/src/db/registry.dart#L57-L58
> 
> 
> They are deleted on every launch, before this block of code.

I don't see any file that ends with "-lck", perhaps it should be ".lock"

**Comment by JaffaKetchup** [comment]
@sikandernoori On Windows at least, there are only '-lck' files:
![image](https://user-images.githubusercontent.com/58115698/222254091-49903ef0-fc58-47aa-b5d2-33381a34c2af.png)
Can you send a screenshot of the FMTC directory on your system?

I have taken your advice as well, and implemented https://github.com/JaffaKetchup/flutter_map_tile_caching/pull/104/commits/585c060ad187d69453db5b1a3cbb4bb8aaf50903, which only processes files with an extension of exactly '.isar'. Therefore, this kind of issue should be avoided anyway.
But I would still like to know if it's '.lock' or '-lck' on your system :)

**Comment by sikandernoori** [comment]
> But I would still like to know if it's '.lock' or '-lck' on your system :)

on Android and IOS it's ".lock"

<img width="1505" alt="Screenshot 2023-03-02 at 1 22 43 PM" src="https://user-images.githubusercontent.com/16399272/222415016-e463128d-4111-4af4-b57b-9375e7b34e15.png">

**Comment by JaffaKetchup** [comment]
OK. I will re-enforce the system again, and delete any files not ending in '.isar'. Thanks for your insight.
