### ISSUE TITLE
[BUG] FMTCStoreNotReady (FMTCStoreNotReady: The store ('TestStore') does not exist at this time, and is not ready.

### ISSUE THREAD

**Issue by sikandernoori** [JaffaKetchup/flutter_map_tile_caching#108]
### What is the bug?

Exception has occurred.
FMTCStoreNotReady (FMTCStoreNotReady: The store ('TestStore') does not exist at this time, and is not ready. Ensure that your application does not use the method that triggered this error unless it is sure that the store will exist at this point.)

### What is the expected behaviour?

Store should Create successfully without exceptions.

### How can we reproduce this issue?

Create Store in example App.

### Do you have a potential solution?

Yes,

```
  Future<void> createAsync() async {
    if (ready) return;  // this is wrong as at this time store is not created.

    final db = await Isar.open(
      [DbStoreDescriptorSchema, DbTileSchema, DbMetadataSchema],
      name: _id.toString(),
      directory: _rootDirectory.path,
      maxSizeMiB: FMTC.instance.settings.databaseMaxSize,
      compactOnLaunch: FMTC.instance.settings.databaseCompactCondition,
      inspector: false,
    );
    await db.writeTxn(
      () => db.storeDescriptor.put(DbStoreDescriptor(name: _name)),
    );
    _registry.register(_id, db);
  }
```

### Platforms Affected

iOS

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] I have checked for known issues in the GitHub tracker and [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#known-issues)
- [X] I have completed the pre-report checks listed [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#reporting-a-bug)
- [X] If I am using FMTC in a proprietary project, I have read and understood [this important legal notice](https://fmtc.jaffaketchup.dev/#proprietary-licensing)

**Comment by JaffaKetchup** [comment]
Hi @sikandernoori,

In this case, the code seems to be OK. If the store already exists (is `ready`), it shouldn't be recreated. However, this error does suggest an issue.

For reference, here's the `ready` code:
```dart
try {
  _registry(_name);
  return true;
  // ignore: avoid_catching_errors
} on FMTCStoreNotReady catch (e) {
  if (e._registered) rethrow;
  return false;
}
```

I can't reproduce with the example app. Can you take a screen recording, or make a minimal reproducible example please?

Many thanks.

**Comment by sikandernoori** [comment]
@JaffaKetchup the issue is present in example App.

Steps to reproduce:

in example app root directory
1. flutter create . (To create ios binaries)
2. update pod file

replace
```
target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```
with

```
target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  use_modular_headers!
end
```
3. Then launch app on IOS device or simulator. (Error present on both in screenshot I am sharing emulator).
4. Create a new store and hit save icon, you will be presented with error.

Moreover if you can see in `_registry(name)` call it's trying to look for store in `_storeDatabases` at create stage it will always return false because you are registering new db at the end of createAsync function.

```
  Future<void> createAsync() async {
    if (ready) return;

    final db = await Isar.open(
      [DbStoreDescriptorSchema, DbTileSchema, DbMetadataSchema],
      name: _id.toString(),
      directory: _rootDirectory.path,
      maxSizeMiB: FMTC.instance.settings.databaseMaxSize,
      compactOnLaunch: FMTC.instance.settings.databaseCompactCondition,
      inspector: false,
    );
    await db.writeTxn(
      () => db.storeDescriptor.put(DbStoreDescriptor(name: _name)),
    );
    _registry.register(_id, db); (This is where you are registering.)
  }
  ```
<img width="1508" alt="Screenshot 2023-02-28 at 12 48 24 AM" src="https://user-images.githubusercontent.com/16399272/221704183-d732281e-21cc-4779-816e-a954d34777b2.png">

**Comment by sikandernoori** [comment]
This screenshot should help more, check stack and variables values on left side.
<img width="1508" alt="Screenshot 2023-02-28 at 1 02 10 AM" src="https://user-images.githubusercontent.com/16399272/221709097-ffd4332f-139d-4436-89ce-cb0d99f73b75.png">

**Comment by JaffaKetchup** [comment]
@sikandernoori Ah I see now.
Indeed, this error is thrown, but it is caught before it causes any issues: this is the way it's intended to function.
As you can see, the error never makes it to the console. Debu mode catches issues a little prematurely.
If you can "Run without Debugging", to ensure that the console only recives uncaught errors, you should be able to verify this behaviour.

**Comment by sikandernoori** [comment]
Upto you, how you want to handle it.
In my opinion exception should not be thrown for creating store.

**Comment by JaffaKetchup** [comment]
@sikandernoori The exeception doesn't make it outside of my library, and it is caught and processed correctly. Within your app, you can 'pretend' it isn't thrown. Therefore, I don't think this is an issue.
