### ISSUE TITLE
[FEATURE] Support `RetryClient`s

### ISSUE THREAD

**Issue by ibraheemalayan** [JaffaKetchup/flutter_map_tile_caching#112]
### What do you want implemented?

Using the library on a testing device with moderate network connection causes some timeouts and crashes the map screen. A simple fix for this issue is to setup some kind of retries on failure.
The easiest way to do that is to use a [Dio](https://pub.dev/packages/dio) client with a retry interceptor or simpler use a [RetryClient](https://pub.dev/documentation/http/latest/retry/RetryClient-class.html) 

The current `instance.getTileProvider` method takes only `HttpClient` as an http client. doesn't accept a [Dio](https://pub.dev/packages/dio) client nor a RetryClient.

Also the `errorHandler` callback in the `FMTCTileProviderSettings` is basically useless since errors are rethrown and there is no way to retry them inside it.

### What other alternatives are available?

currently I did not find any work around

### Platforms Affected

Android, iOS

### Severity

Annoying: Currently have to use workarounds

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] I have checked for similar feature requests which may be duplicates
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map_tile_caching) of this package

**Comment by JaffaKetchup** [comment]
Hi @ibraheemalayan :)

> Also the errorHandler callback in the FMTCTileProviderSettings is basically useless since errors are rethrown and there is no way to retry them inside it.

Unfortunatley, there's literally nothing I can do about this. You'll notice that every image provider is the same. In case of a failure, there are no bytes to return, but bytes must be returned. Therefore, the only option is for an error to be thrown. You can safely ignore this error.

I'm not willing to implement Dio for a multitude of reasons. However, having the option for a retry client seems sensible? But I might check whether I can just do the normal behaviour in the event of a timeout.

Thanks for your request! If you found FMTC useful, please consider donating via the button at the top of the page: any amount is appriciated!
