### ISSUE TITLE
[BUG] dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)

### ISSUE THREAD

**Issue by sikandernoori** [JaffaKetchup/flutter_map_tile_caching#113]
### What is the bug?

When you pan map a little fast and move around then there is this error.

dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)

### What is the expected behaviour?

There should not any error related to too many connections

### How can we reproduce this issue?

When you pan map a little fast and move around then there is this error.

### Do you have a potential solution?

Not yet, but connection should be single with stream, if available. or at least connection should be disposed when finished.

### Can you provide any other information?

Not ATM

### Platforms Affected

iOS

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

### Frequency

Often: Occurs more often than when it doesn't

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] I have checked for known issues in the GitHub tracker and [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#known-issues)
- [X] I have completed the pre-report checks listed [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#reporting-a-bug)
- [X] If I am using FMTC in a proprietary project, I have read and understood [this important legal notice](https://fmtc.jaffaketchup.dev/#proprietary-licensing)

**Comment by JaffaKetchup** [comment]
Hi @sikandernoori,
Please try the #114 branch. You can now set custom `BaseClient`s (such as `HttpClient`s): you may be able to set https://api.dart.dev/stable/2.17.5/dart-io/HttpClient/maxConnectionsPerHost.html to resolve this issue.

**Comment by sikandernoori** [comment]
@JaffaKetchup would be great if you update `getTileProvider` 

https://github.com/JaffaKetchup/flutter_map_tile_caching/blob/3d723ed052f0e27de50e2f3db351ad95e43c5516/lib/src/store/directory.dart#L57-L61

And change optional positional arguments to optional named arguments, so that if someone wants to change last param, he does not have to provide others first.

**Comment by JaffaKetchup** [comment]
@sikandernoori (https://github.com/JaffaKetchup/flutter_map_tile_caching/pull/114#discussion_r1149378696)
