### ISSUE TITLE
The store ('kelkkareitit') does not exist at this time, and is not ready. Ensure that your application does not use the method that triggered this error unless it is sure that the store will exist at this point.

### ISSUE THREAD

**Issue by Abdulah-butt** [JaffaKetchup/flutter_map_tile_caching#116]
### What is the bug?

The store ('kelkkareitit') does not exist at this time, and is not ready. Ensure that your application does not use the method that triggered this error unless it is sure that the store will exist at this point.

### What is the expected behaviour?

import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';

import 'package:latlong2/latlong.dart';
import 'package:http/http.dart' as http;
import 'package:flutter_map/flutter_map.dart';
import 'package:flutter_cache_manager/flutter_cache_manager.dart';
import 'package:flutter_map_tile_caching/flutter_map_tile_caching.dart';

class MapScreen extends StatefulWidget {
  const MapScreen({Key? key}) : super(key: key);

  @override
  State<MapScreen> createState() => _MapScreenState();
}

class _MapScreenState extends State<MapScreen> {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    cacheTiles();

  }

  cacheTiles() async {

  }

  MapController mapController = MapController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Flutter Map Example')),
      body: FlutterMap(
        options: MapOptions(
            center: LatLng(63.1817371, 21.7348336),
            zoom: 9.2,
            onTap: (tapPosition, latLng) {
              print(latLng);
              _handleTap(latLng);
            }),
        mapController: mapController,
        children: [
          // openMapTileLayer,
          // snowMobileTileLayer,
          // TileLayer(
          //   urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
          //   subdomains: ['a', 'b', 'c'],
          // ),
          // TileLayer(
          //   urlTemplate: 'http://tiles.kelkkareitit.fi/kelkkareitit/{z}/{x}/{y}.png',
          //   subdomains: ['a', 'b', 'c'],
          // ),

          TileLayer(
            urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
            //change base_snow_map to pistes
            subdomains: ['a', 'b', 'c'],
            tileProvider: FMTC.instance('kelkkareitit').getTileProvider(),
          ),
          // TileLayer(
          //     urlTemplate:
          //         "http://tiles.kelkkareitit.fi/kelkkareitit/{z}/{x}/{y}.png",
          //     //change base_snow_map to pistes
          //     subdomains: ['a', 'b', 'c'],
          //
          //     backgroundColor: Colors.transparent),
          MarkerLayer(
            markers: _tapPoints
                .map((latLng) => Marker(
                      point: latLng,
                      builder: (context) => GestureDetector(
                        onTap: () {
                          setState(() {
                            _tapPoints.remove(latLng);
                          });
                        },
                        child: const Icon(
                          Icons.location_pin,
                          color: Colors.red,
                          size: 40,
                        ),
                      ),
                    ))
                .toList(),
          ),
          PolylineLayer(
            polylineCulling: false,
            polylines: polylines,
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: Icon(Icons.download),
      ),
    );
  }

  Future<List<LatLng>> _getRouteFromUrl(String url) async {
    http.Response response = await http.get(Uri.parse(url));
    if (response.statusCode == 200) {
      // Parse the response body into a list of LatLng objects
      List<dynamic> data = jsonDecode(response.body);
      List<LatLng> route = [];
      for (dynamic point in data) {
        LatLng latLng = LatLng(point['lat'], point['lng']);
        route.add(latLng);
      }
      return route;
    } else {
      print(response.reasonPhrase);
      print(response.statusCode);

      throw Exception('Failed to load route data');
    }
  }

  List<LatLng> _tapPoints = [];

  List<Polyline> polylines = [];

  void _handleTap(LatLng latLng) async {
    bool markerExists = _tapPoints.any((marker) => marker == latLng);
    markerExists ? _tapPoints.remove(latLng) : _tapPoints.add(latLng);

    if (_tapPoints.length >= 2) {
      Polyline newPolyline = Polyline(
        points: _tapPoints,
        color: Colors.orange,
        strokeWidth: 5.0,
      );
      polylines.add(newPolyline);
      setState(() {});
    }
  }
}

### Platforms Affected

Android, iOS

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] I have checked for known issues in the GitHub tracker and [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#known-issues)
- [X] I have completed the pre-report checks listed [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#reporting-a-bug)
- [X] If I am using FMTC in a proprietary project, I have read and understood [this important legal notice](https://fmtc.jaffaketchup.dev/#proprietary-licensing)

**Comment by JaffaKetchup** [comment]
Hi @Abdulah-butt,
You don't appear to have `create`d the 'kelkkareitit' store (RTFE), but you're trying to use it in the `TileProvider`.
Please make sure you create the store first following the instructions in the docs.

---

_Using FMTC is a proprietary project? Please read [this notice](https://fmtc.jaffaketchup.dev/#proprietary-licensing) about the GPL license attached to this project. Failure to do so, or ignoring the restrictions of the GPL license, constitutes a criminal offence by copyright law._

**Comment by JaffaKetchup** [comment]
Please ask if you need more help. Closing this for now.
