### ISSUE TITLE
Ability to pre-load surrounding tiles when browsing

### ISSUE THREAD

**Issue by JankoLancer** [JaffaKetchup/flutter_map_tile_caching#12]
Hi, thank you for the effort in making this plugin.

I would like to get some clarification:
- Do I need to explicitly call downloadRegion to download a new Area, it does not cache automatically when a tile is downloaded when the map is moved?
- If I call downloadRegion on every map move, do tiles get downloaded again regardless if they are already downloaded and cached?

**Comment by JaffaKetchup** [comment]
Hi there,
Thanks!

In answer to your first question, no, if you use the correct tile provider, it will automatically cache each tile when it becomes visible in the viewframe. The download function is intended if you want to download large areas at once, for example downloading a mountainous area before the user goes there and becomes offline. 

In answer to question 2, you should never need to do this. In fact, this will severely impact performance. But, in answer to whether the image is cached again: if the image is attempted to be cached via the download function, it will be downloaded again; but if the tile provider (automatic) is used (when the map is panning), then the tile won't be cached unless it's new or invalid.

I hope this clears up any questions, but feel free to ask more if you need to :)!

I'll also take a look at the way I write documentation for V3, to try and make this immediately clear.

**Comment by JaffaKetchup** [comment]
https://github.com/JaffaKetchup/flutter_map_tile_caching/pull/11#issuecomment-872529909

**Comment by JankoLancer** [comment]
Thanks for the clarification. One more question, why I am still getting empty gray tiles even when using this plugin?

**Comment by JaffaKetchup** [comment]
Grey tiles can still happen if the user is offline and browses undownloaded tiles.
Alternatively this may be a bug. Is there any output to the console?

**Comment by JankoLancer** [comment]
Tiles are definitely downloaded, because I turn off internet to test it. Tiles are showed but grey tiles are showed for the part of the second every time I move.

**Comment by JaffaKetchup** [comment]
Ah, I see. This is due to the time it takes to retrieve the tile from the database. The time this shows for depends on the speed and processing power of the device, as well as the size of the database. You'll probably notice this when getting a tile from the internet as well.

**Comment by JankoLancer** [comment]
I hoped that can be bypassed by caching, but yeah, it is faster with caching.

Thanks!

**Comment by JankoLancer** [comment]
@JaffaKetchup Do you think it could be possible to preload into memory some of the tiles (neighbor) so moving could be lot smoother without grey tiles?

**Comment by JaffaKetchup** [comment]
That is a good idea, loading the neighbouring tiles, and it might be possible?
I'll see what I can do, but it won't be part of v3. Maybe v3.1?

**Comment by JankoLancer** [comment]
@JaffaKetchup yes, but I don't if this can be done in your plugin? I thought of preloading tiles in the memory, so that we bypass grey tiles. If you have some ideas on how this can be done, I can help, this would be the most powerful addition to flutter_map or your plugin.

**Comment by JaffaKetchup** [comment]
Well, I think it should be possible by getting the number of tiles shown at once on a screen, then loading the surrounding tiles of the tiles currently loaded by just incrementing the fetch tile number to get the tile adjacent.

I agree, it would be quite good, so if you're sure you don't mind helping, so help would be greatly appreciated! Feel free to fork and make a PR!

**Comment by JankoLancer** [comment]
I need this for my personal project, grey tiles are so frustrating and ugly...

**Comment by JaffaKetchup** [comment]
Yeah, I can understand that. I'll start working on it asap.

**Comment by JaffaKetchup** [comment]
Ok, so it's coming along slowly.
There's a few limitations with flutter_map that I'm having to overcome/workaround, but I think it's possible as I have a very basic version working.

**Comment by JaffaKetchup** [comment]
Unfortunately, this will not be possible for the foreseeable future, due to the issues mentioned in https://github.com/fleaflet/flutter_map/issues/966. If it becomes possible in the future, I will reopen this issue, but for now it will be closed because it is blocked indefinitely.

If this library helps you, please consider liking, starring or even potentially donating!

**Comment by JaffaKetchup** [comment]
As visible at https://github.com/fleaflet/flutter_map/issues/966, it may be possible to introduce this functionality.

**Comment by JaffaKetchup** [comment]
Unfortunately, due to the long amount of time that this is taking to develop, this feature will become a part of Version 5 in the future.

If you would like to help, please feel free to submit a PR based off of the v4 branch!

**Comment by JankoLancer** [comment]
Hi, is this closed as finished or as not possible to do?

**Comment by JaffaKetchup** [comment]
Hi there, this is closed because it is (at least for now) impossible due to restrictions in `flutter_map`. Apologies if this is a problem.

If you would like to investigate more, feel free to submit a PR to the v4 branch. Thanks.
