### ISSUE TITLE
[BUG] IOS malloc_error_break crash

### ISSUE THREAD

**Issue by eidolonFIRE** [JaffaKetchup/flutter_map_tile_caching#121]
### What is the bug?

Crash on launch. (including the very first launch with v7)

iOS: 16.1.1
Flutter: 3.7.12
FMTC: 7.2.0

I have the `isar` dependency fix in place and it works fine on Android.
```
dependency_overrides:
  isar: 3.0.6-dev.0
  isar_flutter_libs: 3.0.6-dev.0
```

```
flutter: ╔══════════════════════════════════════════════════════════╗
flutter: ║                   ISAR CONNECT STARTED                   ║
flutter: ╟──────────────────────────────────────────────────────────╢
flutter: ║           Open the link to connect to the Isar           ║
flutter: ║          Inspector while this build is running.          ║
flutter: ╟──────────────────────────────────────────────────────────╢
flutter: ║ https://inspect.isar.dev/3.0.6-dev.0/#/60346/9JQf1qJWK0Y ║
flutter: ╚══════════════════════════════════════════════════════════╝
Runner(75844,0x16ed4f000) malloc: *** error for object 0xffffffffffffffff: pointer being freed was not allocated
Runner(75844,0x16ed4f000) malloc: *** set a breakpoint in malloc_error_break to debug
* thread #33, name = 'isarworker', stop reason = signal SIGABRT
    frame #0: 0x00000001c86a0200 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1c86a0200 <+8>:  b.lo   0x1c86a0220               ; <+40>
    0x1c86a0204 <+12>: pacibsp
    0x1c86a0208 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1c86a020c <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.
```

I'm migrating to v7 (from v6) and following the example provided here in the repo. Unfortunately, iOS just crashes while Android is fine.

Any hints or suggestions welcome 👍 
Maybe someone has seen this before or has some intuition on where to start looking.

Is it even worth looking into? Should I just jump back to `/v6-backporting` ?

### What is the expected behaviour?

Expected isar system comes up...

### Platforms Affected

iOS

### Severity

Fatal: Causes the application to crash

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] I have checked for known issues in the GitHub tracker and [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#known-issues)
- [X] I have completed the pre-report checks listed [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#reporting-a-bug)
- [X] If I am using FMTC in a proprietary project, I have read and understood [this important legal notice](https://fmtc.jaffaketchup.dev/#proprietary-licensing)

**Comment by eidolonFIRE** [comment]
( I did see #118 , btw. I felt mine looked a bit different. 🤷 Maybe it's the same? )

**Comment by JaffaKetchup** [comment]
Hey @eidolonFIRE, can you try the v8 prerelease? It's stable, and just waiting for the next FM release. It might fix your issue, as it uses Isar 3.1.0 which had some stability fixes.

**Comment by JaffaKetchup** [comment]
Hey @eidolonFIRE, v8 has now been released with Isar v3.1 & flutter_map v4 support. 
This issue looks like it might be fixed by Isar v3.1, so please give it a try and let me know if it resolved your issue.

**Comment by eidolonFIRE** [comment]
I got started upgrading to FM v4 / FMTC v8.  Unfortunately, it broke too many of my plug-ins and features, so that'll have to wait till I have bandwidth to pull forward everything I'm using (prolly next quarter).

In the meantime, I've reverted to `v6-backporting`.

Thank you so much for all the hard work! FMTC is an important part of my app. ❤️

**Comment by JaffaKetchup** [comment]
Sure, no problem at all. If you can spare any change, please consider donating if you haven't already - it's always appreciated!
