### ISSUE TITLE
[BUG] fmtc_plus_background_downloading version solving filed.

### ISSUE THREAD

**Issue by DonWasyl** [JaffaKetchup/flutter_map_tile_caching#125]
### What is the bug?

I'm trying update dependencies to the newest versino, but during fetching packages I've got error:

```
Because every version of fmtc_plus_background_downloading depends on flutter_map_tile_caching ^7.0.0 and grupa_biwakowa depends on flutter_map_tile_caching ^8.0.0, fmtc_plus_background_downloading is forbidden.
So, because grupa_biwakowa depends on fmtc_plus_background_downloading ^7.0.0, version solving failed.
```

### How can we reproduce it?

Try to add to pubspec.yml

```
  flutter_map_tile_caching: ^8.0.0
  fmtc_plus_background_downloading: ^7.0.0
  fmtc_plus_sharing: ^8.0.0
 ```

### Platforms

Android, iOS

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by JaffaKetchup** [comment]
Hi @DonWasyl,
I'll update the package today.

**Comment by DonWasyl** [comment]
Thanks for instant response ;)

**Comment by JaffaKetchup** [comment]
No problem. v8 should be out now.
