### ISSUE TITLE
Issues related to WMS tile layer options (WMSTileLayerOptions not caching)

### ISSUE THREAD

**Issue by Ram8948** [JaffaKetchup/flutter_map_tile_caching#126]
### What is the bug?

I am using flutter_map_tile_cache lib to cache tile but I am not able to cache WMSTileLayerOptions layers please provide any solution

### How can we reproduce it?

 TileLayer(
        wmsOptions: WMSTileLayerOptions(
          baseUrl: 'https://apps.xyz.com:8080/myserver/wms/?',
          layers: ['XYZLAYER:stateboundary],
          format: 'image/png',
          transparent: true,
        ),
        backgroundColor: Colors.transparent,
        userAgentPackageName: 'com.example.xyz',
        tileProvider: FMTC.instance('mapStore').getTileProvider(),
      ),

### Platforms

Android 11 Samsung Galaxy A30s

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
Hi @Ram8948,
Does it work if you use a standard tile layer? Have you created the store? Can you query the statistics to check whether tiles are being written?

**Comment by Ram8948** [comment]
yes, it works on the standard tile layer and I have created the store.

**Comment by JaffaKetchup** [comment]
Ok, thanks for the info. Are there any errors in console? What does the DevTools Network tab say about the tile requests? Can you print out the store statistics?
