### ISSUE TITLE
[BUG] Issue with IOS [Impeller] v3.10 +

### ISSUE THREAD

**Issue by jesussmile** [JaffaKetchup/flutter_map_tile_caching#128]
### What is the bug?

Okay, so with the new Flutter IOS rendering  Impeller, there seems to be an issue rendering on IOS, it is causing quite some memory leak and freezing

### How can we reproduce it?

Just load overlay Image, clear it and reload another

### Do you have a potential solution?

You may want to check the new impeller documentation, After remove this plugin everything worked fine. took quite a while to debug.

### Platforms

ios

### Severity

Fatal: Causes the application to crash

**Comment by JaffaKetchup** [comment]
Hey @jesussmile,

Can you be a little more detailed? What do you mean with this:

> Just load overlay Image, clear it and reload another

**Comment by JaffaKetchup** [comment]
Note that you may be getting #118, instead of a new Impeller issue. How can you verify that this is an Impeller issue?

**Comment by jesussmile** [comment]
Apologies for not being clear, When i use your plugin and an overlay image it will work the first time but If i add another overlayImage dynamically it will give me this error
```
════════ Exception caught by image resource service ════════════════════════════
The following _Exception was thrown resolving an image frame:
Exception: Could not create Impeller texture.

When the exception was thrown, this was the stack
Image provider: AssetImage(bundle: null, name: "assets/charts/VNKT/fly_nepal_charts/JCHART/JCHART_CROPPED_Page_015.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#d8ca0(), name: "assets/charts/VNKT/fly_nepal_charts/JCHART/JCHART_CROPPED_Page_015.png", scale: 1.0)
```
So, I thought it was an issue with my code or something, I just couldn't duplicate it. Then i started to remove plugin one by one. Unfortunately, when i removed yours it started to work.

To duplicate this issue. You may want to load overlayImages dynamically onto the map.  If you want I can create you a sample project but I am out on training might take a while.

**Comment by JaffaKetchup** [comment]
Hey @jesussmile,
It isn't FMTC that provides overlay images? Did you mean to file this in the FM tracker?

**Comment by jesussmile** [comment]
I honestly don't know how to explain this,  Yes you are correct, I am using FMTC and overlayImage from `flutter_map`. I have simply loaded an overlayImage onto the map, then I clear the overlay image and load another , this is when i get the Impeller Error, works fine when I am not using FMTC.
Ah! you may close this as it isn't directly related, If I come up with something substantial I will reopen it ? or create a sample project.

**Comment by JaffaKetchup** [comment]
@jesussmile Thanks for confirming. For the moment, I'm going to close this. If you can confirm the issue comes from something bad/poor FMTC is doing, rather than just FMTC working as it should, please feel free to reopen!
Thanks for reporting, it's good to keep this on my radar.
