### ISSUE TITLE
[BUG] flutter_map_tile_caching ^8.0.1 requires latlong2 ^0.8.0

### ISSUE THREAD

**Issue by george-brandidea** [JaffaKetchup/flutter_map_tile_caching#134]
### What is the bug?

Because flutter_map_tile_caching 8.0.1 depends on latlong2 ^0.8.0 and no versions of flutter_map_tile_caching match >8.0.1 <9.0.0, flutter_map_tile_caching ^8.0.1 requires latlong2 ^0.8.0.
So, because locaview_flutter depends on both latlong2 ^0.9.0 and flutter_map_tile_caching ^8.0.1, version solving failed.
exit code 1

I am not able to use the latest version. Please update this.

### How can we reproduce it?

Update the version

### Platforms

Android

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by george-brandidea** [comment]
It doesn't support with the version latlong2: ^0.9.0

**Comment by JaffaKetchup** [comment]
Hey @george-brandidea,
FMTC is currently in upgrade for v9. The latest prerelease on pub.dev causes issues, but the latest commit on the 'v8.1.0' branch (ignore the name) should be compatible with the latest FM v6 prerelease.

**Comment by george-brandidea** [comment]
Currently I'm using flutter_map version 4. To use the version 5 it's asking latlong2: ^0.9.0. Although I need to update other packages also like FMTC.

**Comment by JaffaKetchup** [comment]
Try a dependency override to pin an appropriate latlong2 version. AFAIK, 0.8.0 and 0.9.0 are compatible enough for that not to cause any issues.

**Comment by JaffaKetchup** [comment]
A fresh prerelease of this will be released when FM v6 is ready. Then, I need to work on some other bits and pieces around the database, which I'm not sure how long that will take.

**Comment by JaffaKetchup** [comment]
The latest FM prerelease supports FM v6.
