### ISSUE TITLE
[BUG] V9 won't resolve to a stable flutter SDK

### ISSUE THREAD

**Issue by eidolonFIRE** [JaffaKetchup/flutter_map_tile_caching#142]
### What is the bug?

Tried the v9 (branch: v8.1.0) , but the package `meta` won't resolve to any stable release of flutter.

https://github.com/JaffaKetchup/flutter_map_tile_caching/blob/v8.1.0/pubspec.yaml#L40

You can see it pinned to a < version here:
https://github.com/flutter/flutter/blob/3.16.3/packages/flutter/pubspec.yaml#L13

### How can we reproduce it?

-

### Do you have a potential solution?

Can `meta` be rolled back to `1.10.0` ?

### Platforms

na

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
@eidolonFIRE Whoops, thanks for reporting this. You can use a dependency override as a workaround for the time being.

**Comment by eidolonFIRE** [comment]
I'm gonna have to just wait... (or wait for backporting?).
Too many incompatibilities with common packages like `package_info_plus`, `wakelock`, `wakelock_plus` etc... Even when I try to get them all pre-release git branches, it's turtles all the way down.
