### ISSUE TITLE
[BUG] When use with latlong application crashes  

### ISSUE THREAD

**Issue by AliAltiyev** [JaffaKetchup/flutter_map_tile_caching#143]
### What is the bug?

../../.pub-cache/hosted/pub.dev/flutter_map_tile_caching-9.0.0-dev.5/lib/src/db/tools.dart:16:16: Error: The integer literal 0xcbf29ce484222325 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in JavaScript. In JavaScript 0xcbf29ce484222000 is the nearest value that can be represented exactly.
    int hash = 0xcbf29ce484222325;
               ^^^^^^^^^^^^^^^^^^

### How can we reproduce it?

 return TileLayer(
    tileProvider: FMTC.instance('mapStore').getTileProvider(
            settings: FMTCTileProviderSettings(
          cachedValidDuration: const Duration(
            days: 30,
          ),
          behavior: CacheBehavior.cacheFirst,
        )),
    urlTemplate:
        'https://api.mapbox.com/styles/v1/lukart/clmtemm5w00m801qnahut57nf/tiles/{z}/{x}/{y}@2x?access_token=$token',
    additionalOptions: <String, String>{
      'accessToken': token,
      'id': 'mapbox.dark',
    },
    retinaMode: false,
    tileSize: 512,
    backgroundColor: Colors.white,
    zoomOffset: -1,
    subdomains: const <String>['a', 'b', 'c'],
  );
}

### Do you have a potential solution?

should decrement version of latlong from 0.9.0 to 0.8.0

### Platforms

Android 13 (Hotfix Note 30) 

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
Hi @AliAltiyev,
This issue has been previously reported. It prevents web compilation and could cause a warning when compiling for other platforms.
v9 will resolve this issue. Please follow #96.
