### ISSUE TITLE
[BUG] Isar v4 compatibility

### ISSUE THREAD

**Issue by yakou32** [JaffaKetchup/flutter_map_tile_caching#145]
### What is the bug?

I'm trying to use the latest version of FMTC, that supports Isar v4:
> [9.0.0] - 2023/XX/XX  - Migrated to Isar v4 (bug fixes & stability improvements)

However, there seems to be some incompatibilities:
`[my app] depends on flutter_map_tile_caching ^9.0.0-dev.5 which depends on isar ^3.1.0+1, isar ^3.1.0+1 is required`

### How can we reproduce it?

These are the versions I use in `pubspec.yaml`:
```
flutter_map_tile_caching: ^9.0.0-dev.5
isar: ^4.0.0-dev.14
```

### Do you have a potential solution?

I couldn't find the v9 repo to check the pubspec file.
So, I was enquiring here...

### Platforms

Android 13

### Severity

Fatal: Causes the application to crash

**Comment by JaffaKetchup** [comment]
Hi @yakou32,
Sorry for the confusion. V9 does not actually use Isar V4. It was my original intention, which is why it is in the CHANGELOG, but will not happen - I'm migrating to ObjectBox.
