### ISSUE TITLE
When i download tiles shown only once. After application restarted all tiles gone. But evenry setting is okay.

### ISSUE THREAD

**Issue by zarifergashev** [JaffaKetchup/flutter_map_tile_caching#146]
### What is the bug?

When i download tiles shown only once. After application restarted all tiles gone. But evenry setting is okay.

### How can we reproduce it?

When i download tiles shown only once. After application restarted all tiles gone. But evenry setting is okay.

### Platforms

Samsung A32 Android 13 

### Severity

Minimum: Allows normal functioning

**Comment by zarifergashev** [comment]
this is initialise code 
`Future<void> initFlutterMapTileCaching() async {
  try {
    await FlutterMapTileCaching.initialise(
      debugMode: true,
      rootDirectory: null,
      errorHandler: (error) => MyLog.error(error.message),
    );

    await FMTC.instance(OfflineMapPref.FIRST_STORE).manage.createAsync();
    await FMTC.instance(OfflineMapPref.SECOND_STORE).manage.createAsync();
  } catch (e, st) {
    MyLog.error(e, st);
  }
}`

**Comment by zarifergashev** [comment]
<img width="722" alt="Screenshot 2024-02-04 at 17 13 59" src="https://github.com/JaffaKetchup/flutter_map_tile_caching/assets/37806412/2850bee0-322f-4869-8cd8-7c4906189bbb">

**Comment by JaffaKetchup** [comment]
Hi @zarifergashev,
Thanks for reporting this, it is quite unusual. Please double check everything, and ensure you are not resetting anything (also remove the `null` argument passed to `rootDirectory` because it is unnecessary), and create an entire MRE - otherwise I'll find this difficult to reproduce.
