### ISSUE TITLE
[BUG] Could not resolve all files for configuration ':objectbox_flutter_libs:androidApis'

### ISSUE THREAD

**Issue by mtourne** [JaffaKetchup/flutter_map_tile_caching#152]
### What is the bug?

After upgrading from 9.0.0-dev5; when switching to ObjectBox I'm guessing, when building I'm getting this error 

```
* What went wrong:
Execution failed for task ':objectbox_flutter_libs:parseReleaseLocalResources'.
> Could not resolve all files for configuration ':objectbox_flutter_libs:androidApis'.
   > Failed to transform android.jar to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for PlatformAttrTransform: /Users/mtourne/Library/Android/sdk/platforms/android-31/android.jar.
         > /Users/mtourne/Library/Android/sdk/platforms/android-31/android.jar

```

### How can we reproduce it?

building after upgrading flutter_map_tile_caching

### Platforms

Android 

### Severity

Fatal: Causes the application to crash

**Comment by JaffaKetchup** [comment]
Hi @mtourne,

Thanks for reporting this! It would be great if you could attach a minimally reproducible example with Android configuration, just to see if I can reproduce this (as I can't, and it's not directly an issue with this package). Build errors like this are usually hard to reproduce across systems though.

It might also be worth deleting all your existing platform SDKs (this can be done manually or in Android Studio I believe), and reinstalling the necessary ones. You may also want to try on a different device, particularly with a different OS version if you have one.

Unfortunately I can't help too much more than this with the current info. It's likely to be a misconfiguration hidden in your build config or enviroment somewhere.

**Comment by mtourne** [comment]
I added all the .gradle files and a listing of all files; let me know if you'd like to see something else here 

[find.txt](https://github.com/JaffaKetchup/flutter_map_tile_caching/files/15129884/find.txt)

**Comment by JaffaKetchup** [comment]
Can you try the suggestion here: https://stackoverflow.com/a/73636286/11846040?
