### ISSUE TITLE
V6 Backporting Branch Gone?

### ISSUE THREAD

**Issue by RedHappyLlama** [JaffaKetchup/flutter_map_tile_caching#160]
### What is the bug?

It seems the V6 Backporting branch is gone (https://github.com/JaffaKetchup/flutter_map_tile_caching/tree/v6-backporting)? I was using this to avoid Isar stability issues. I am also not yet able to migrate to V9 due to other dependencies. Is there another way to use the V6 Backporting version? Current method in pubspec.yaml below:

`dependency_overrides:
  flutter_map_tile_caching:
    git:
      url: https://github.com/JaffaKetchup/flutter_map_tile_caching.git
      ref: v6-backporting
`

As a result of this, map does not load at all. 

### How can we reproduce it?

Use the following in pubspec.yaml:

`dependency_overrides:
  flutter_map_tile_caching:
    git:
      url: https://github.com/JaffaKetchup/flutter_map_tile_caching.git
      ref: v6-backporting
`

### Platforms

Android and iOS

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by RedHappyLlama** [comment]
Issue resolved using a local version. Could still be worthwhile fixing the link?

**Comment by RedHappyLlama** [comment]
Issue resolved using a local version. Could still be worthwhile fixing the link?

**Comment by JaffaKetchup** [comment]
The v6 backport was removed when v9 was published, as it was intended to avoid stability issues with Isar between in v7 and v8. The backport is now too great of a maintainence burden to keep running, especially as v9 should be much more stable, as it no longer relies on Isar.

If the backport is required, I've attached the ZIP of the latest state of the branch. If you need it published to pub.dev, please let me know.

Please note that the license within the ZIP still applies exactly the same as it would if the source code was being served externally.

[flutter_map_tile_caching-6-backporting.zip](https://github.com/user-attachments/files/16199564/flutter_map_tile_caching-6-backporting.zip)
