### ISSUE TITLE
[BUG] Failed to load dynamic library 'libobjectbox-jni.so' on Android

### ISSUE THREAD

**Issue by jdszekeres** [JaffaKetchup/flutter_map_tile_caching#161]
### What is the bug?

When creating an application with Flutter Maps and FMTC on Android, the app reports `Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libobjectbox-jni.so': dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/~~e4HrudegL2A1VvRCapKg2A==/com.example.app-RKmrSd5vX7gLi7_bptFz3Q==/lib/x86_64/libobjectbox-jni.so" (new hash type from the future?)`. This prevents any tiles from being loaded. 

### How can we reproduce it?

Here is the relevant part of my pubspec.yaml
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_map:
  flutter_map_tile_caching: ^9.0.1
```

Here is the class I use to interface with FMTC

```dart
import 'package:flutter_map/flutter_map.dart';
import 'package:flutter_map_tile_caching/flutter_map_tile_caching.dart';
final tileLayer = TileLayer(
  urlTemplate:
      'https://api.maptiler.com/maps/hybrid/{z}/{x}/{y}.jpg?key=JPWduKmbflkklrVwwG14',
);
class StoreService {
  // Private constructor
  StoreService._privateConstructor();
  // Singleton instance
  static final StoreService _instance = StoreService._privateConstructor();
  // Factory constructor to return the singleton instance
  factory StoreService() {
    return _instance;
  }
  final store = const FMTCStore("tileStore");
  bool initialized = false;
  Future<void> initialize() async {
    if (!initialized) {
      initialized = true;
      await FMTCObjectBoxBackend().initialise();
      await store.manage.create();
    }
  }
  Stream<DownloadProgress> downloadTiles({
    required BaseRegion region,
    required int minZoom,
    required int maxZoom,
    required TileLayer layer,
  }) {
    initialize();
    FMTCStore store = const FMTCStore("tileStore");
    var progress = store.download.startForeground(
        parallelThreads: 5,
        region: region.toDownloadable(
          minZoom: minZoom,
          maxZoom: maxZoom,
          options: layer,
        ));
    return progress;
  }
}
```

### Platforms

Android Emulator sdk gphone16k x86 64

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by JaffaKetchup** [comment]
Hi @jdszekeres,
Thanks for reporting. Just as a preliminary step, can you perform a `flutter clean` and restart your emulator, to see if that helps?

**Comment by jdszekeres** [comment]
I just performed a `flutter clean` and restarted the emulator. The emulator is a Pixel Fold on API Version 35. Unfortunately, I do not have a physical device to test on, but I still get the error when building for release.

**Comment by JaffaKetchup** [comment]
Android 15 is still in beta. Does this issue occur on lower Android versions (say Android 12, 13)?

**Comment by jdszekeres** [comment]
The app works as expected in Android 13.

**Comment by JaffaKetchup** [comment]
In that case, I'm going to mark this as won't fix. If Android 15 gets to release and this is still an issue, it'll need to be raised with ObjectBox.
Thanks for reporting!
