### ISSUE TITLE
downloadRegion() method only stores in 'mainCache'

### ISSUE THREAD

**Issue by Chinolox** [JaffaKetchup/flutter_map_tile_caching#17]
Hi, I have 2 tile providers with different `cacheName` and when I navigate with them on the map, they are saved correctly in their respective storage. However when I try to download regions for each with `downloadRegion()`, they are always saved in 'mainCache' instead of the specified one. 
Is this intentional? If not, is there any way to download maps into separate storages?

**Comment by JaffaKetchup** [comment]
Just looked through the code on my mobile, that's definitely a bug (I can see where it is).

The fix should (hopefully) only take a couple minutes so I'll try to have it done by midday tomorrow (I'm in UK it's 10pm).

That shouldn't have slipped through my tests, I'll try to be more thorough in the future, sorry.

Thanks for reporting!

**Comment by JaffaKetchup** [comment]
All done, released to pub.dev as v3.0.1. Thanks once again!

If this library helps you, please consider liking, starring or even potentially donating!

**Comment by Chinolox** [comment]
I just tested it and it works perfectly. Thank you very much.

**Comment by JaffaKetchup** [comment]
Sure, no problem :)
