### ISSUE TITLE
[BUG] Exception on macOS when trying to initialise FMTCObjectBoxBackend

### ISSUE THREAD

**Issue by Errechydy** [JaffaKetchup/flutter_map_tile_caching#174]
### What is the bug?

I get this exception when trying to run the app:
`
[ERROR] Storage error "Operation not permitted" (code 1)
flutter: StorageException: failed to create store: Could not open database environment; please check options and file system (1: Operation not permitted) (OBX_ERROR code 10199)
`

### How can we reproduce it?

Run this code:
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Object? initErr;
  try {
    await FMTCObjectBoxBackend().initialise();
  } catch (err) {
    initErr = err;
    print("Error initialising FMTC: $err");
  }
// .......
  }
```

### Do you have a potential solution?

The only solution to make it run is by turning off sandbox, which is something that shouldn't be done in production
`
	<key>com.apple.security.app-sandbox</key>
	<false/>
`

### Platforms

macOS 15.1 

### Severity

Fatal: Causes the application to crash

**Comment by JaffaKetchup** [comment]
Hi @Errechydy,

Please follow the setup guide for ObjectBox at https://docs.objectbox.io/getting-started for macOS. There's a parameter in the init method to pass in the application group I think.

![Screenshot_2024-12-27-14-22-23-595_com.android.chrome.png](https://github.com/user-attachments/assets/958ea0bd-fcad-4ddf-b860-c0e939729f4e)

Let me know if that doesn't work!

**Comment by Errechydy** [comment]
Hi @JaffaKetchup 
Thanks a lot, it did work.
I think there should be a reference to this in the `flutter_map_tile_caching` docs. because when someone sees `macOS` is supported he would assume it would work out of the box without any extra configurations.  And the problem is searching about the exception i got didn't show that the issue was in the parameter in the init method.
Thanks again

**Comment by JaffaKetchup** [comment]
Yep, it should indeed be in the docs, apologies! I forgot to add it when I started using ObjectBox.
