### ISSUE TITLE
Cannot compile android version of the app "Could not find any matches for com.transistorsoft:tsbackgroundfetch:+"

### ISSUE THREAD

**Issue by zeykafx** [JaffaKetchup/flutter_map_tile_caching#19]
**What is the bug?**
Whenever the plugin is added in the pubspec.yaml file the app will not compile (tested in a clean/new project)

**What do you expect to happen?**
the app should compile when the plugin is added in the pubspec.yaml file....

**Reproduction**
Steps to reproduce the behaviour:
1. Create a new flutter project
2. add the plugin in the pubspec.yaml file like this `flutter_map_tile_caching: ^3.0.1`
3. run the app on a real device or emulator
4. notice the error

**Screenshots and recordings**
build error:
![image](https://user-images.githubusercontent.com/37271973/126766246-e7c93597-a456-4ec1-b9d2-7b6540d16657.png)

**Additional context**
error message: Launching lib\main.dart on SM T860 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/D:/coren/PROGRAMMING/FLUTTER/Metar-Viewer/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by zeykafx** [comment]
this seems to be the proper way to implement it 
https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md
as explained in https://github.com/transistorsoft/flutter_background_fetch/issues/204

**Comment by zeykafx** [comment]
Im sorry, I didn't read the whole readme, this is embarrassing...

**Comment by JaffaKetchup** [comment]
Don't worry about it! :)

**Comment by zeykafx** [comment]
It's just that I had it working for 2 weeks or so and I never made those changes to the build.gradle files, so I wasn't sure why it wasn't working now 😆

**Comment by JaffaKetchup** [comment]
Not sure, that change was added in the v3 update, so before that, it wasn't necessary, but after that, it should've been necessary from my testing. Gradle is just like that sometimes! Out of interest, what platform are you developing for?

**Comment by zeykafx** [comment]
Yeah, actually I updated my fork a few days ago but it was still working then. Gradle confuses me 😅
