### ISSUE TITLE
Duration and tile amount settings not used

### ISSUE THREAD

**Issue by rcsousa14** [JaffaKetchup/flutter_map_tile_caching#20]
This is more a question on how the package work. I would like to know if there is a way to increase the caching time (i believe  currently is 30 or 31 days) also can I increase the number of tiles that could be downloaded to the phone. Thank you so much for the package :)

**Comment by JaffaKetchup** [comment]
Hi,
You should be able to do this through `cachedValidDuration` in the tile provider.
However, I have just looked and realised I've made a mistake in my code (setting defaults and not passing other values through) which means this won't work.
Sorry about this, I'll try to fix it before the end of today!

**Comment by JaffaKetchup** [comment]
All done, released to pub.dev as v3.0.2. Thanks once again!

If this library helps you, please consider liking, starring or even potentially donating!

**Comment by rcsousa14** [comment]
thank you so much!

**Comment by JaffaKetchup** [comment]
Sure, no problem.
