### ISSUE TITLE
Ability to delete a downloaded region

### ISSUE THREAD

**Issue by Abdelrahman-Sherif** [JaffaKetchup/flutter_map_tile_caching#24]
**Describe the solution you'd like**
An option to delete a region from the database when it is no longer needed.

**Is your feature request related to a problem? Please describe.**
There is currently no method to delete a region. The only viable option is to clear data/re-download the app which is not sustainable.

**Describe alternatives you've considered**
No options currently available other than clearing the app data.

**Additional context**

**Comment by Abdelrahman-Sherif** [comment]
I dug deeper into the code, and found the TileStorageCachingManager class, which has a static cleanCacheName method. This is what I needed. It was not mentioned in the documentation, so please add it to help future users. Thanks for the support and the great package!

**Comment by JaffaKetchup** [comment]
Hi there, I'm not changing documentation in the future due to the abundance (90%+ of public API elements) of in-code docs available from the API Reference link on pub.dev. In v4, there will be little documentation in the README.

**Comment by GaelleJoubert** [comment]
@Abdelrahman-Sherif I have the same need than you, but I did not find the class "TileStorageCachingManager "...
could you tell me exactly where it is ? 
Thanks a lot.

**Comment by GaelleJoubert** [comment]
> Hi @GaelleJoubert, This is from an older version of FMTC

Hi, thanks for the reply. So there is no way of deleting only a region now ?

**Comment by JaffaKetchup** [comment]
Hi @GaelleJoubert,
I'm assuming this Issue was created before stores were introduced, because deleting a region doesn't make sense: they are formed of tiles that get absorbed into the database just like any other tiles.
You can delete stores.

**Comment by GaelleJoubert** [comment]
Well, for my apps it would make sense.
The user can choose to save some specific area of the map (custom or actual country regions), to have them accessible for later use in offline mode. 
And it would be nice if the user could chose to delete the downloaded regions individually, if he wants to free some space in his phone for exemple, but still keep some.

Unless I misUnderstood the ways store function, this is not really possible is it ?
Like it would feel super weird to create a new store for each "new" region, there will be duplicate tiles.

**Comment by JaffaKetchup** [comment]
Hi @GaelleJoubert,

I see now. This should be done via multiple stores at the moment, as that's the finest level of control. It's true that this will cause duplication however.

If I get time, I'll have a look at implementing this into v7. However, how would you refer to the region to delete? Providing coordinate bounds would be too expensive, so that's not an option. The only other method is to be able to name regions. Would that suit you?

I'm cautious about implementing this feature, I don't want to overcomplicate things too much.

**Comment by GaelleJoubert** [comment]
@JaffaKetchup That would be amazing if this can be a feature in the future ! :)
Yes, to be able to name Regions would be great.
I was thinking maybe adding a method to a DownloadableRegion or a BaseRegion (whichever is the easiest for you), something like BaseRegion.Delete() which would delete the Tiles which are in the Region.

The "only" complicated thing I see is that if you have Two Region which overlaps. I see two options for that :
- Region.delete() alway delete all the tiles  in that region, it does not care if you have another region wich overlaps.
- Something like Region.delete(excludeFromDelete: [Region2(), Region3, ...] ), wich would delete the tiles from Region, and if any Region from the list of Region overlaps, it does not delete the Overlapping Tiles.

Maybe you can see another option for this issue, you know the architecture of the library better than me !

Thank you for your time :)

**Comment by JaffaKetchup** [comment]
@GaelleJoubert If I implement it (which I'm still not 100% sure about), it'll be:

- A region can be downloaded with a name
- A tile has multiple owning region names + 'browseCached'
- Deleting a region by name will remove it's name from all it's tiles
- A tile with no owning regions (and one that is not 'browseCached') will be deleted

Note that this is relativley expensive in terms of both database space/capacity (a new index will be necessary) and performance.

**Comment by GaelleJoubert** [comment]
Great ! 
That would be amazing, and I would be super interested in such a feature! :)
Thanks you very much for considering it.

**Comment by JaffaKetchup** [comment]
@GaelleJoubert Please see #83.
