### ISSUE TITLE
Support Flutter 2.5

### ISSUE THREAD

**Issue by hauphidao** [JaffaKetchup/flutter_map_tile_caching#26]
Please update to support Flutter 2.5.

**Comment by JaffaKetchup** [comment]
Hi there, does this package not already support Flutter 2.5?
Please elaborate.

**Comment by JaffaKetchup** [comment]
Hi there,
Support for Flutter version 2.5 is on it's way in Version 4. Unfortunately, v4 is taking more time to develop than expected, but hopefully it should be available soon.

**Comment by JaffaKetchup** [comment]
Please use the pre-releases (latest as of writing: https://pub.dev/packages/flutter_map_tile_caching/versions/4.0.0-dev.5) to get this functionality early.

**Comment by JaffaKetchup** [comment]
Closing as v4.0.0 gets closer to release-ready. Only remain on v3 if required or if you absolutely cannot use beta libraries.
