### ISSUE TITLE
Offline side loading

### ISSUE THREAD

**Issue by AAverin** [JaffaKetchup/flutter_map_tile_caching#30]
**Describe the solution you'd like**
I would like to be able to prepare offline pack beforehand on my server and side-load or download it in runtime, enabling and disabling this offline pack on demand.

**Comment by JaffaKetchup** [comment]
Hi there!

Just interested, have you considered using the method under the Offline Maps With Tilemill in the main `flutter_map` repository's README?
If not, please double check, as it sounds similar to what your asking for. It may be too much effort/impossible on your machine (I've looked into that method before), in which case I totally understand, and we can talk through your idea in a bit more detail just so I can implement it correctly.

If it isn't, just say, and we can talk through your idea in a bit more detail just so I can implement it correctly.

Thanks for your interest, and it sounds like your idea has the potential for a great new addition :)

**Comment by AAverin** [comment]
@JaffaKetchup Provided documentation suggests to put everything into assets folder, my plan is to download offline packages in runtime.
I will need to experiment with TileMill to see if it can cover this usecase, for now I am using Mapbox implementation.
Still, it would be great to know if something like I want is possible before I invest too much time and effort into TIlemill solution.

**Comment by JaffaKetchup** [comment]
Ok, I can see how you would want this, perhaps to manage a large number of devices at scale?

Would a solution where:
1. The admin starts a special bulk download that 'zips' all of the downloaded tiles into an archive
2. That archive can then be shared/moved somewhere easily accessible
3. The admin or a user can 'upload' (not really uploading) that archive to the app
4. The app unzips it and puts it in the correct place

...work for you?

The issues on my side looking at this libraries development are:
 - This could take a long time to code and test
 - This involves asking for potentially 'dodgy' permissions to access external storage
 - Inability to test on iOS: I don't have a Mac or iPhone

Hopefully I can overcome these issues similar to how I handled background downloading - only available on Android and separate function to ask for permissions.

Does the above implementation sound good for your situtation?

**Comment by AAverin** [comment]
The way I do it now is:
- there is an automated script that generates offline tile packages and puts them into storage
- storage is accessible via API
- client can request a download of the offline package and "enable" it in mapbox implementation

I am looking to replace mapbox with something else and searching for solutions that support offline side-loading well.

All the maps that I generate are unique per user.

**Comment by JaffaKetchup** [comment]
Ok, this should be even easier to implement then?

Assuming you can generate the required tiles as .png or .jpg with the correct tile names (format can be decided later) and archive it on a server, then it should be simple to download a whole archive and un-archive it when necessary.

Does this better suit your needs?

**Comment by JaffaKetchup** [comment]
Hi there,
Did you find anything that did what you needed, or do you still need this to be added?
Thanks!

**Comment by AAverin** [comment]
Sorry, didn't yet have time to investigate. Probably Tilemill should work to some extent
