### ISSUE TITLE
[QUESTION] How to cache specific area?

### ISSUE THREAD

**Issue by take2make** [JaffaKetchup/flutter_map_tile_caching#33]
What is the easiest way to cache specific areas in detail? I want not just to cache one layer of the area, but also have the ability to observe map details.

**Comment by JaffaKetchup** [comment]
Hi there,
Thanks for your interest.
Can you please elaborate on what you mean by 'in detail' and 'map details'?
Thanks :).

**Comment by take2make** [comment]
I mean, I try to scale map in cache mode, and after cached layer only gray screen I can see without any details. These are map details)

**Comment by JaffaKetchup** [comment]
The map can only load the tiles that have been cached and/or are accessible online: grey means no tiles available.

If I'm misunderstanding (which is likely), please send a screen recording or more detailed explanation.

**Comment by JaffaKetchup** [comment]
Hi there,
Have I answered your question or do your require more help?

**Comment by take2make** [comment]
Nope, thanks!
