### ISSUE TITLE
[BUG] v4: Example app (randomly?) crashes

### ISSUE THREAD

**Issue by take2make** [JaffaKetchup/flutter_map_tile_caching#34]
I load the example app on the Emulator. After some time switching to cache application stopped with this error:

Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x304 in tid 3084 (DartWorker), pid 2710 (le.fmtc_example)

**Comment by JaffaKetchup** [comment]
I also receive this bug, I just relaunch the app. As v4 is still in development, however, I will not fix this until release.

**Comment by take2make** [comment]
Hm, do you have some mode in such I can load specific area in all scales?

**Comment by JaffaKetchup** [comment]
Do you mean bulk downloading? If so, this is available, but not complete in the example: use the API, and please read README for more info.

**Comment by take2make** [comment]
Can you also send a working example for the current stable version (not v4)? Because this example (https://pub.dev/packages/flutter_map_tile_caching/example) isn't working.

**Comment by JaffaKetchup** [comment]
Go to the main branch on GitHub, or visit v3.0.(can't remember the iteration) on Pub.dev.

Note that the example may still be a little buggy: I never put much time into it until now.

**Comment by take2make** [comment]
About bulk downloading. Unfortunately, I couldn't find any information about it. Could you please send me a link where I can read how to use it?

**Comment by JaffaKetchup** [comment]
Please see https://pub.dev/documentation/flutter_map_tile_caching/latest/flutter_map_tile_caching/StorageCachingTileProvider/downloadRegion.html and other API documentation, and the README where it talks about `downloadRegion()`

**Comment by JaffaKetchup** [comment]
Closing for the meanwhile for the reasons mentioned above. Workaround: relaunch the application.

**Comment by JaffaKetchup** [comment]
See #39.
