### ISSUE TITLE
[QUESTION] Possible to disable all caching temporarily?

### ISSUE THREAD

**Issue by take2make** [JaffaKetchup/flutter_map_tile_caching#36]
Can I disable caching if switch button? I do not want to cache data if I have the Internet. But If I don't have the Internet I wanna get cached data first.

**Comment by JaffaKetchup** [comment]
Hi,
Thinking that means you are only using bulk downloading then.

In that case, that is possible.
Have a boolean variable in a stateful widget (containing the map). Use the ternary (?:) operator to choose the standard tile provider (not mine) or the caching tile provider.
You may also need to setup reset functionality on the map - see the `reset` property on the tile layer; there is an example in 'flutter_map' to help you if you need it.

Hope this works for you!

**Comment by JaffaKetchup** [comment]
As a side note, please try to use the issue templates in the future. They make sure I have more of the information I need and automatically set correct labels etc..

**Comment by JaffaKetchup** [comment]
Hi there,
Has this resolved your issue? I'd be happy to help more if necessary.
Thanks!

If this library helps you, please leave a like on [pub.dev](https://pub.dev/packages/flutter_map_tile_caching) and a star on [GitHub](https://github.com/JaffaKetchup/flutter_map_tile_caching), and potentially consider [donating](https://ko-fi.com/JaffaKetchup): it really helps!

**Comment by JaffaKetchup** [comment]
Hi there,
I'm assuming your issue is resolved, so I will close this issue soon. If you do still need help, please just comment and I'd be happy to.
Thanks!
