### ISSUE TITLE
Question - Loading tiles takes much time

### ISSUE THREAD

**Issue by take2make** [JaffaKetchup/flutter_map_tile_caching#37]
When I try loading 200 MB tiles download continuous much time. How can I reduce this time?

**Comment by JaffaKetchup** [comment]
Hi,
Could you please tell me roughly how long it takes, and the number of tiles? 200MB is a lot of tiles, I think.
Thanks.

**Comment by take2make** [comment]
10000 tiles, more than 10 minutes

**Comment by JaffaKetchup** [comment]
Unfortunately, this could depend on internet connection speed a lot. If you don't mind me asking, approximately how fast is your connection?

**Comment by JaffaKetchup** [comment]
For example, I just downloaded ~9500 tiles (~200MB) in <5 mins on 65 MBPS download speed on a Xiaomi Redmi Note 10 Pro.

**Comment by JaffaKetchup** [comment]
Hi there,
Has this resolved your issue? I'd be happy to help more if necessary.
Thanks!

If this library helps you, please leave a like on [pub.dev](https://pub.dev/packages/flutter_map_tile_caching) and a star on [GitHub](https://github.com/JaffaKetchup/flutter_map_tile_caching), and potentially consider [donating](https://ko-fi.com/JaffaKetchup): it really helps!
