### ISSUE TITLE
[BUG] On some Android devices download button doesn't work

### ISSUE THREAD

**Issue by take2make** [JaffaKetchup/flutter_map_tile_caching#38]
I added bulk downloading to my application. On some android devices in production doesn't work download button. What can be the reason?

**Comment by JaffaKetchup** [comment]
Hi there,

Are you using background downloading? If so, try setting the `useAltMethod` to `true`. This should be stable on most devices, but uses an older API.

What have you passed to the `preDownloadChecks` argument? If you left it at null, then devices must be connected to the Internet on WiFi and have >15% battery charge. You can change this, see the documentation.

**Comment by JaffaKetchup** [comment]
Hi there,
Did you fix your problem? I can still help if needed?
Thanks.

**Comment by take2make** [comment]
preDownloadChecks - What should I pass here as arguments to download also without wifi? I couldn't find information in the documentation

**Comment by JaffaKetchup** [comment]
To skip all checks just make the argument null. For docs see `PreDownloadChecksCallback`.

**Comment by JaffaKetchup** [comment]
Hi there,
Did you fix your problem? I can still help if needed?
Thanks.

**Comment by JaffaKetchup** [comment]
Will close now as invalid as there was no response. Please add a comment if you need it reopened.

Thanks!
