### ISSUE TITLE
[BUG] 'flutter_local_notifications' Integration Error

### ISSUE THREAD

**Issue by sikandernoori** [JaffaKetchup/flutter_map_tile_caching#41]
### Versions 
Flutter versionL: 2.10.1
Dart 2.16.1 
DevTools 2.9.2

### Getting below error:
```
../../../.pub-cache/hosted/pub.dartlang.org/flutter_map_tile_caching-3.0.3/lib/src/main.dart:182:45: Error: Too many positional arguments: 2 allowed, but 3 found.
Try removing the extra positional arguments.
                  AndroidNotificationDetails(
                                            ^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.2.0/lib/src/platform_specifics/android/notification_details.dart:12:9: Context: Found this candidate, but the arguments don't match.
  const AndroidNotificationDetails(
```

Issue us related to flutter_local_notifications function AndroidNotificationDetails, description parameter has been changed to named parameter.

For details, have a look [documentation](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails-class.html)

**Comment by JaffaKetchup** [comment]
Hi, thanks for your report and fix! I'm probably misunderstanding, but surely if the version isn't upgraded, then this issue won't happen, as it happened in a newer version?

**Comment by sikandernoori** [comment]
I used the existing version and it was happening for me even with lower version of flutter_local_notifications.

See the documentation and change log of flutter_local_notifications.

**Comment by JaffaKetchup** [comment]
Ok, I'll try to have this merged in some form or another by the end of today. Thanks!

**Comment by sikandernoori** [comment]
Appreciated !

**Comment by JaffaKetchup** [comment]
@sikandernoori Note that it may be beneficial to you to use v4.0.0-dev.x versions. These versions are stable since v4.0.0-dev.12, and v4 will be released within a week or two. v4 has an almsot completely different API, and so you would save time not having too write your code again.

**Comment by sikandernoori** [comment]
@JaffaKetchup
I Just checked v4 branch.
 
[breaking change](https://github.com/JaffaKetchup/flutter_map_tile_caching/blob/aa5436bc5fb88e9652ea25ca8473e92a170a13e6/lib/src/main.dart#L372)

You are right. Looking forward to v4 release.
