### ISSUE TITLE
[BUG] v4: File system watching is not supported on this platform (iOS)

### ISSUE THREAD

**Issue by meli27** [JaffaKetchup/flutter_map_tile_caching#43]
Hello! When I run the v4 `example`  on iPad Air 4th gen (iOS 14.5) it returns this

```
═══════ Exception caught by widgets library ═══════════════════════════════════
The following FileSystemException was thrown building Consumer<GeneralProvider>(dirty, dependencies: [_InheritedProviderScope<GeneralProvider?>]):
File system watching is not supported on this platform, path = ''

The relevant error-causing widget was
Consumer<GeneralProvider> Consumer:[file:///Users/melissavillalobos/Downloads/flutter_map_tile_caching-4/example/lib/pages/home/components/panel/panel.dart:26:16]()
When the exception was thrown, this was the stack
.....
```
I already added the background_fetch and permission_handler configurations.
I am not sure if I did something wrong , hope someone can help, thanks.

**Comment by JaffaKetchup** [comment]
Hi there, thanks for your report.
It appears that you haven't done anything wrong on your side, as the example app should be preconfigured.
The panel in that example uses `MapCachingManager.watchStoreChanges()`, which internally uses `.watch()` from 'dart:io'. The error would lead me to believe that that method is not supported on iOS, but the official documentation contradicts that:

> - Linux: Uses `inotify`. The implementation supports watching both files and directories. Recursive watching is not supported. Note: When watching files directly, delete events might not happen as expected.
> - OS X: Uses `FSEvents`. The implementation supports watching both files and directories. Recursive watching is supported.

(I'm not sure which iOS comes under, I think it comes under OS X)

I see that you have downloaded the code onto your device. Could you please add some code just to help me debug (I can't test iOS): `print()` out the `parentDirectory.path` in use, then send that string on here . You can find this by awaiting `MapCachingManager.normalCache`, perhaps in the `main()` method? This would be a huge help, as I can see that the path that it's supposedly watching is empty.

Thanks.

**Comment by meli27** [comment]
Hello, got it. 

Right now is printing this 
<img width="696" alt="Screen Shot 2022-02-23 at 14 57 36" src="https://user-images.githubusercontent.com/50907677/155407251-87433771-0654-47b8-900c-7114591dcab2.png">

`flutter: [/Users/melissavillalobos/Library/Developer/CoreSimulator/Devices/CCD52F2D-F674-4FBE-A5F3-185408E7C7FB/data/Containers/Data/Application/9011A34B-E6B0-4BF8-85B9-B3B676BA0C8D/Documents/mapCache]()`

**Comment by JaffaKetchup** [comment]
It seems the path is correct. Can you read through https://github.com/gradle/gradle/issues/14944, and see if anything might apply to your development environment? Many thanks.

**Comment by JaffaKetchup** [comment]
Oops, sorry for that last comment. That was unrelated.
It seems the path is correct, but I'm not sure why the platform support is wrong. I will do some more digging, but (as I said before) I am very limited in my methods to debug iOS.

**Comment by JaffaKetchup** [comment]
I am planning to release whilst this bug is still present. Should it become a big issue, I will try to allocate more hours to solving this, but I am unfortunately quite busy at the moment.
If you have anymore information, please do comment here. Thanks!

**Comment by akeblom** [comment]
I am getting the same issue.

**Comment by JaffaKetchup** [comment]
Can you both update to the latest version, and let me know if you now receive another error? Many thanks.

**Comment by akeblom** [comment]
Yes indeed. Now I get the unsupported error.

**Comment by JaffaKetchup** [comment]
Unfortunately, this is unresolvable then, as this is not this library's limitation. If you agree with my above comments (that this looks like it could be a bug in Flutter), I'd suggest creating a bug report there and linking here.
Thanks for your reports! If you can donate, please do - Kofi doesn't take a fee!

**Comment by meli27** [comment]
[](https://github.com/flutter/flutter/issues/99456)

**Comment by meli27** [comment]
https://github.com/flutter/flutter/issues/99456
