### ISSUE TITLE
[BUG] iOS - Filename too long

### ISSUE THREAD

**Issue by akeblom** [JaffaKetchup/flutter_map_tile_caching#45]
The tileserver we are using returns very long filename. On iOS this makes caching fails with the following exception:

```FileSystemException (FileSystemException: Cannot open file, path = '/var/mobile/Containers/Data/Application/5649CAC6-88DA-4FA5-8E59-C982E99F69CC/Documents/mapCache/Test/https___testmaps-v2.metria.se_geoserver_metria_wms_&service=WMS&request=GetMap&layers=metria%3AMetriaFastighetLafayette&styles=&format=image%2Fpng&srs=EPSG%3A3857&version=1.1.1&transparent=true&width=256&height=256&bbox=2392631.859382587,9689463.453542082,2392784.7334391577,9689616.327598657' (OS Error: File name too long, errno = 63))```

@ line 80 downloader.dart

```
File(path).writeAsBytesSync(
      (await client.get(Uri.parse(url))).bodyBytes,
      flush: true,
    );
```

**Comment by JaffaKetchup** [comment]
Thanks for your report!

This seems to be a limitation of the operating system in iOS unfortunately, as it can only handle up to 255 chars in a filename.

I will try to fix by only taking the last 255 chars of a string.
This should be published by the end of today as v4.0.1.

If you have any more information, please let me know. Many thanks!

**Comment by JaffaKetchup** [comment]
_In the future, please consider making use of the provided templates. Thanks._

**Comment by akeblom** [comment]
How will that work when trying load the cached tile against the actual url?

**Comment by JaffaKetchup** [comment]
It should be ok, as long as the same process is done on either side.

**Comment by JaffaKetchup** [comment]
Should be all merged, will release soon. Please donate if you can!
