### ISSUE TITLE
[BUG] [v5.0.0-dev.2] `startForeground` doesn't trigger `onDone` event

### ISSUE THREAD

**Issue by Lukiya** [JaffaKetchup/flutter_map_tile_caching#53]
**Describe The Bug**
startForeground stream won't tigger onDone event.

**Expected Behaviour**
onDone event should be triggered like 4.xx version.

**Additional Information**

Version: 5.0.0 dev2

---

**Doctors Report**

```shell
[✓] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.22000.739], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.2)
[✓] Android Studio (version 2020.3)
[✓] VS Code, 64-bit edition (version 1.68.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**To Reproduce**

```dart
 FMTC.instance["test"].download.startForeground(region: cacheRegion).listen(
        (dp) {
            debugPrint("Dowloading..."); // Works
        },
        onDone: () async {
            debugPrint("onDone"); // Won't trigger
        },
        onError: (err) {
             debugPrint("onError");
        },
);

```

---

**Severity**
This will help us to label the issue quicker and decide what needs attention first. Only choose fatal if the entire app crashes, otherwise choose non-fatal.

- [x] Non-Fatal
- [ ] Fatal / App Crashes

**Frequency/Rarity**
This will help us to label the issue quicker and decide what needs attention first.

- [ ] Once
- [ ] Uncommon
- [ ] Common
- [x] Always

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] Others (beta platforms)

**Comment by JaffaKetchup** [comment]
Thank you for the report!

Do the tiles still get downloaded correctly during the download? Can you temporarily workaround by checking the percentage complete is 100?

**Comment by JaffaKetchup** [comment]
This percentage check is supposed to be done internally, but I guess I accidentally removed it. I'll add it back :)

**Comment by sn4k3ch4rm3r** [comment]
I don't know how it works, or why it works, but if you remove the `await` from [lib/src/store/download.dart:281](https://github.com/JaffaKetchup/flutter_map_tile_caching/blob/a01d3c488e519ce667ceba9f60d2fcb064b41c3f/lib/src/store/download.dart#L281), it does trigger `onDone()`.

**Comment by JaffaKetchup** [comment]
Hmm, that's interesting. That would suggest the stream isn't being closed properly, which needs to happen. Thanks for the heads up!

**Comment by JaffaKetchup** [comment]
Fixed in the latest versions of v5. Thanks for the report!
