### ISSUE TITLE
[FEATURE] [v5.0.0] General Questions & Ideas

### ISSUE THREAD

**Issue by paul-gdy** [JaffaKetchup/flutter_map_tile_caching#56]
Hi

I have implemented the v5 in my project and it looks great on android and ios.

However here are some questions / suggestions :
- [#31](https://github.com/JaffaKetchup/flutter_map_tile_caching/issues/31) is present, but solved with `PaintingBinding.instance?.imageCache?.clear();`
- Headers should be implemented as in flutter_map, maybe : `await httpClient.get(Uri.parse(url), headers: options.tileProvider.headers);` in image_provider.dart.
- The bulk download requires several permissions for its dependencies (background_fetch, battery_info, connectivity_plus, flutter_local_notifications). Would it be possible to split flutter_map_tile_catching between the cache manager and the bulk download and thus avoid these dependencies if they are not useful ?
- In my project I would like to display a map and a layer. Is it possible to have 2 FMTC.instance based on 2 different stores ? Is there a trick to implement this ?

Thanks

**Comment by JaffaKetchup** [comment]
Hi there, glad to hear it's working for you.

- Using this method is the correct workaround, but not recommended, as this will reload all the images in your app.
- Headers in this package will be implemented after https://github.com/fleaflet/flutter_map/pull/1294 is merged. I will also implement a custom 'User-Agent', something along the lines of 'flutter_map/flutter_map_tile_caching (<packageName>)'.
- This could be a possibility, however, I'm not sure I'm willing to do this. It would be harder to maintain and more things to update when other packages are updated.
- It is possible to use two stores at once, although using them on the map at the same time may cause problems (I think someone raised this issue to me, but I can't remember where). Using two roots is currently not easily possible, without using `initialise` every time you need to change it.

If you have any more questions, let me know!

**Comment by paul-gdy** [comment]
Thank you for your answer.

I confirm that trying to access two maps at the same time (eg for a layer) is not consistent. If tiles are in different stores or in the same store.

**Comment by paul-gdy** [comment]
As I really need to access two different maps at the same time, I have implemented [flutter_cached_network_image](https://github.com/Baseflow/flutter_cached_network_image) combined with [flutter_cache_manager](https://github.com/Baseflow/flutter_cache_manager).

I have not looked in depth at the differences with your plugin but I get similar cache implementation and management.

**Comment by JaffaKetchup** [comment]
@paul-gdy The issue of being able to use two maps at the same time should've just been resolved!

**Comment by JaffaKetchup** [comment]
@paul-gdy Additonally, #31 has been fixed in the latest v5 branch commits!

**Comment by paul-gdy** [comment]
Thank you ! I will try this soon.
