### ISSUE TITLE
[FEATURE] Get The size of tiles in kilobytes before downloading

### ISSUE THREAD

**Issue by mohammedX6** [JaffaKetchup/flutter_map_tile_caching#60]
I think it's useful to let the user know how much the download size takes before starting bulk downloading.

**Applicable Platforms**
Select platforms that this request applies to.

- [x] All/any
- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] Others (beta platforms)

**Comment by JaffaKetchup** [comment]
Hi there, and thanks for your interest.

This is, unfortunately, impossible, as there is no guaranteed API endpoint to get the size of a specific tile, and not all tiles are the same size.

**Comment by mohammedX6** [comment]
thanks for let me know.
