### ISSUE TITLE
[BUG] Error: No named parameter with the name 'number'.

### ISSUE THREAD

**Issue by bmason8** [JaffaKetchup/flutter_map_tile_caching#65]
After upgrading to `flutter_map_tile_caching: ^5.1.0` (also happens on ^5.1.1) I get an error while building for Android and iOS. I'm on a test branch upgrading to Flutter v_3... as well as some other packages so it could be something else but it seems like there is some type of issue.

```
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_map_tile_caching-5.1.1/lib/src/internal/exts.dart:137:9: 
Error: No named parameter with the name 'number'.
        number: number ?? this.number,
        ^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.5.3+1/lib/src/platform_specifics/android/notification_details.dart:12:9: 
Context: Found this candidate, but the arguments don't match.
  const AndroidNotificationDetails(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/userName/Developer/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/userName/Developer/flutter/bin/flutter'' finished with non-zero exit value 1
```

---

**Doctors Report**

```shell
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

```

---

**Severity**
This will help us to label the issue quicker and decide what needs attention first. Only choose fatal if the entire app crashes, otherwise choose non-fatal.

- [ ] Non-Fatal
- [x] Fatal / App Crashes

**Frequency/Rarity**
This will help us to label the issue quicker and decide what needs attention first.

- [ ] Once
- [ ] Uncommon
- [ ] Common
- [x] Always

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] Others (beta platforms)

**Comment by JaffaKetchup** [comment]
Hi again, and thanks for the report.

I migrated to Flutter v3 a while ago (and migrated this library to v3 on the v5 update), and I am unable to reproduce this issue.
Can you zip up your project so I can try building it on my system? This is probably the quickest way of reproducing it.

Many thanks :)

**Comment by JaffaKetchup** [comment]
Just realised, of course, that is assuming you can do that.
If not, I'll see what I can do, but it might be difficult.

**Comment by bmason8** [comment]
Yeah unfortunately this is a work project so can't send it.
However, I did just create a temporary flutter project and used all the same dependencies and I didn't have any issues building or launching it so I think it must be something wonky in my project.

You can close/delete this issue. Sorry for the inconvenience!

**Comment by JaffaKetchup** [comment]
Ah no problem at all :) Maybe a weird dependency conflict or something like that.
