### ISSUE TITLE
[BUG] Unhandled Exception: Instance of `QueueCancelledException`

### ISSUE THREAD

**Issue by RuijinYao** [JaffaKetchup/flutter_map_tile_caching#68]
### What is the bug?

When I run the following code to cancel the download， the following exception is reported

```
await FMTC
        .instance(provider.selectedStore!.storeName)
        .download
        .cancel();
```

```
 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'QueueCancelledException'
``` 

### What is the expected behaviour?

catch this exception or else ?

### Platforms Affected

Android

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map_tile_caching) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @RuijinYao,

I am aware of the issue, and I could not find a suitable way to ignore the error: you can safely ignore them, they will not affect any functioning.

I will have a deeper look to see if anything can be done, but for the time being, please just ignore the message.

Many thanks!

**Comment by RuijinYao** [comment]
Indeed, the exception does not cause the application to crash;
If there is a follow-up solution, please let me know， Thanks.

**Comment by sikandernoori** [comment]
following this issue

**Comment by JaffaKetchup** [comment]
Finally, managed to find out where this was occurring. Fix will arrive in v8.
