### ISSUE TITLE
[BUG] Uploading to TestFlight issue.

### ISSUE THREAD

**Issue by yaroslav13** [JaffaKetchup/flutter_map_tile_caching#69]
### What is the bug?

Library affects uploading to Testflight. I hope it's happened because of the permission handler or file picker, maybe. 

Predication: 
1. Apple for me now doesn't send emails with warnings and doesn't display builds with warnings for me (Apple side issue).

I think [flutter_map_tile_caching](https://github.com/JaffaKetchup/flutter_map_tile_caching) provoke some warning on Apple side. 

### What is the expected behaviour?

The project appears on Testflight without warnings.

### How can we reproduce this issue?

```dart
1. Add [flutter_map_tile_caching](https://github.com/JaffaKetchup/flutter_map_tile_caching) to project
2. Projects don't appear on Testflight. (for me, for others I think it will be a warning)
```

### Do you have a potential solution?

Maybe we need to document that we need to annotate something in Info.plist according to the permission handler.

### Platforms Affected

iOS

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map_tile_caching) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by yaroslav13** [comment]
Maybe because of that - Any iOS version below 11.0, will require an Apple Developer Program account to enable CloudKit and make it possible to use the document picker (which happens when you select FileType.all, FileType.custom or any other option with getMultiFilePath()). You can read more about it [here](https://developer.apple.com/library/archive/documentation/DataManagement/Conceptual/CloudKitQuickStart/EnablingiCloudandConfiguringCloudKit/EnablingiCloudandConfiguringCloudKit.html).

**Comment by JaffaKetchup** [comment]
Hi @yaroslav13,
Sorry but I'm struggling to understand the issue. Can you please make sure that you follow those library's installation instructions, and let me know if that works? If I'm misunderstanding, please explain again!

**Comment by yaroslav13** [comment]
Hi. I don't find specific installation instructions for iOS. The problem is that Testflight builds do not appear with this library as a dependency. I hope this is because happens you using some dependencies like permission handler or file piker and we missing some annotation in info.plist according to this libs.

**Comment by JaffaKetchup** [comment]
I see. Unfortunately I cannot test development on iOS. Are you saying that I need to add something to info.plist?

**Comment by yaroslav13** [comment]
I think yes. I search now for what actually we need to specify)

**Comment by yaroslav13** [comment]
https://github.com/miguelpruivo/flutter_file_picker/wiki/Setup#ios

**Comment by JaffaKetchup** [comment]
@yaroslav13 I'm not sure I'm actually able to add these, because my 'plugin' isn't actually a plugin in terms of Flutter definitions, it's just a package. Therefore, I think this will have to be added on your side?

**Comment by yaroslav13** [comment]
Yep, it helps. Yes, we need to annotate it in the documentation as an additional setup for iOS.

**Comment by yaroslav13** [comment]
You can prevent the need for certain permissions by excluding compilation of Media, Audio or Documents picker respectively. This is achieved by including in the file <project root>/ios/Podfile the line Pod::PICKER_MEDIA = false, resp. Pod::PICKER_AUDIO = false, resp. Pod::PICKER_DOCUMENT = false before the line target 'Runner' do.

(If you do use a file picker that is included an error will be logged and no dialog is shown.)

Based on the location of the files that you are willing to pick paths, you may need to add some keys to your iOS app's Info.plist file, located in <project root>/ios/Runner/Info.plist:

UIBackgroundModes with the fetch and remote-notifications keys - Required if you'll be using the FileType.any or FileType.custom. Describe why your app needs to access background taks, such downloading files (from cloud services). This is called Required background modes, with the keys App download content from network and App downloads content in response to push notifications respectively in the visual editor (since both methods aren't actually overriden, not adding this property/keys may only display a warning, but shouldn't prevent its correct usage).

<key>UIBackgroundModes</key>
<array>
   <string>fetch</string>
   <string>remote-notification</string>
</array>

**Comment by JaffaKetchup** [comment]
So you're saying I just need to add links to the packages' setup instructions in my docs, and maybe a link to your most recent comment? Again, I have little idea how iOS development works, so I'm not quite sure what to write.

If you want to write something, please send it here and I'll be happy to add and credit you!

**Comment by yaroslav13** [comment]
Ok. I think we can write something like this:

![flutter_map_tile_caching](https://github.com/JaffaKetchup/flutter_map_tile_caching) uses
 ![flutter_file_picker](https://github.com/miguelpruivo/flutter_file_picker) as a dependency and required additional configuration for iOS.

Firstly, we need to annotate that we don't need access to Media/Audio and Documents folders. We use only [FileType.custom].

You can achieve it by adding these lines to your Podfile.

```
Pod::PICKER_MEDIA = false
Pod::PICKER_AUDIO = false
Pod::PICKER_DOCUMENT = false
```

before 

`target 'Runner' do `

Second, we need to add [UIBackgroundModes] capability with the [fetch] and [remote-notifications] keys to Xcode to describe why your app needs to access background tasks, such as downloading files (from cloud services). This is called Required background modes, with the keys App download content from network and App downloads content in response to push notifications respectively in the visual editor (since both methods aren't actually overridden, not adding this property/keys may only display a warning, but shouldn't prevent its correct usage).

Docs: https://github.com/miguelpruivo/flutter_file_picker/wiki/Setup#--ios

**Comment by JaffaKetchup** [comment]
Ok, thanks @yaroslav13 for reporting. I'll add this to the docs then close this issue.
I'm just developing a x26 speed improvement in calculating regions, so there'll be an update soon. I'll change the docs along with that release.

**Comment by JaffaKetchup** [comment]
@yaroslav13 That update is taking a bit longer than expected, so I've made those changes now. Please let me know if they work for you: https://fmtc.jaffaketchup.dev/get-started/additional-setup.

**Comment by yaroslav13** [comment]
> @yaroslav13 That update is taking a bit longer than expected, so I've made those changes now. Please let me know if they work for you: https://fmtc.jaffaketchup.dev/get-started/additional-setup.

Yep, great!

**Comment by JaffaKetchup** [comment]
Thanks for your help!
