### ISSUE TITLE
[BUG] `checkTileCached` method appears broken

### ISSUE THREAD

**Issue by caini1213** [JaffaKetchup/flutter_map_tile_caching#72]
### What do you want implemented?

Download cached map tiles as image file permanently, so that i can use map when offline.

### Platforms Affected

Android

### Severity

Annoying: Currently have to use workarounds

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map_tile_caching) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi there @caini1213,

You've exactly described the whole purpose of this library. Can you be more specific about what you need implementing, or what you need help with?

**Comment by caini1213** [comment]
Hi, there

I would like to store the tiles permanently as image file instead of caching it in url, and I saw u had raised some issues about this features at "https://github.com/fleaflet/flutter_map/issues/795", by using network_to_file_image library. So would like to ask that had u solves or implemented this features in ur library? Would u mind to share it? Tq

**Comment by JaffaKetchup** [comment]
@caini1213 This library does exactly that. It stores each tile as an image on the user's device. It is both more reliable and safer than traditional caching, for reasons I won't go into now, but this library still maintains the name caching, because it technically is.

**Comment by JaffaKetchup** [comment]
Note that a completely custom implementation is used here: it does not use the library mentioned in that thread.

**Comment by caini1213** [comment]
How to get the image file (png / jpg) of the cached tile?

**Comment by JaffaKetchup** [comment]
Can I ask why you need to do that?

**Comment by caini1213** [comment]
As I noticed, there is a limited cached duration but store the tile permanently would be better.

**Comment by JaffaKetchup** [comment]
If you read the documentation on that property, you can find how to turn it off. For example, IntelliSense in VSCode.

**Comment by JaffaKetchup** [comment]
I can't remember myself right now, but I know there's a way of doing it, so ^

**Comment by JaffaKetchup** [comment]
@caini1213 Just found it. Try setting it to `Duration.zero`. This should disable it.

**Comment by caini1213** [comment]
https://user-images.githubusercontent.com/58871500/197142598-886f77ff-d9dc-4716-9271-3e29855656ed.mp4

**Comment by JaffaKetchup** [comment]
@caini1213 That video seems to be showing correct functioning? Is something still not working for you?

**Comment by caini1213** [comment]
Alright, but the problem is when I zoom the map, the red color downloaded region will cover the region that I didnt choose to download.

**Comment by JaffaKetchup** [comment]
Ok, it might look wrong, but this is actually correct.

As you zoom out, tiles cover a larger area. For example, a tile at zoom level 18 might only cover one residential street, whereas a tile at zoom level 11 might show a whole city.

Therefore, the further you zoom out, the more of the map will be downloaded - but only at that zoom level. As you can see when you zoom back in, ~half the area becomes non-red again. You can try increasing the minimum zoom level if you don't want the whole world downloaded at zoom level 1.

It is impossible to download any fraction of a tile except one whole, so you'll notice that all bulk downloaders have this behaviour.

**Comment by caini1213** [comment]
![image](https://user-images.githubusercontent.com/58871500/197144114-b52ab352-e7e0-47c5-9c51-f76d23b34369.png)

Currently I'm using ^5.1.0 version, from the image above, the .checkTileAsync() function is to check whether the tile is cached from the store selected right? Can u help me to see if there is any mistake here? Because whenever I load the cached tiles, the red color region will cover over my map (no matter zoom in or out) instead of covering only the downloaded region.

**Comment by JaffaKetchup** [comment]
Can you post a video of this behaviour, or is it the same as the one above?

**Comment by caini1213** [comment]
https://user-images.githubusercontent.com/58871500/197148703-db3f404b-2f60-43e2-8f59-b92cf5b94e5c.mp4

**Comment by caini1213** [comment]
the region is downloaded with zoom level 16 - 20

**Comment by caini1213** [comment]
child: FlutterMap(
                        mapController: mapController,
                        options: MapOptions(
                          keepAlive: true,
                          center: this._centerLocation,
                          minZoom: 12,
                          maxZoom: 20,
                          zoom: 16,
                          interactiveFlags:
                              InteractiveFlag.all & ~InteractiveFlag.rotate,
                          onMapCreated: (MapController controller) {
                            controller.onReady.then((value) {
                              if (!this.widget.isViewDownloadedMap) {
                                _calculateLatLngBound(controller);
                              }
                            });
                          },
                        ),
                        children: [
                      TileLayerWidget(
                          options: TileLayerOptions(
                        maxZoom: 20,
                        urlTemplate:
                            'http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}',
                        tileProvider: this.widget.isViewDownloadedMap
                            ? FMTC
                                .instance(this.widget.viewStoreName!)
                                .getTileProvider()
                            : NetworkNoRetryTileProvider(),
                        // ? AdvancedTileCachedProvider(
                        //     this.widget.viewStoreName)
                        // : NetworkNoRetryTileProvider(),
                        tileBuilder: (context, widget, tile) =>
                            FutureBuilder<bool?>(
                          future: !this.widget.isViewDownloadedMap ||
                                  this.widget.viewStoreName == null
                              ? Future.sync(() => null)
                              : FMTC
                                  .instance(this.widget.viewStoreName!)
                                  .getTileProvider()
                                  .checkTileCachedAsync(
                                    coords: tile.coords,
                                    options: //tileLayerOptions
                                        TileLayerOptions(
                                            maxZoom: 20,
                                            urlTemplate:
                                                'http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}',
                                            tileProvider: FMTC
                                                .instance(
                                                    this.widget.viewStoreName!)
                                                .getTileProvider()),
                                  ),
                          builder: (context, snapshot) => DecoratedBox(
                            position: DecorationPosition.foreground,
                            decoration: BoxDecoration(
                              color: (snapshot.data ?? false)
                                  ? Colors.deepOrange.withOpacity(0.33)
                                  : Colors.transparent,
                            ),
                            child: widget,
                          ),
                        ),
                      )),
                      MarkerLayerWidget(
                          options: MarkerLayerOptions(markers: this._markers)),
                      MarkerLayerWidget(
                          options: MarkerLayerOptions(
                              markers: [this._centerMarker])),
                      MarkerLayerWidget(
                          options:
                              MarkerLayerOptions(markers: this._ouMarkers)),
                      if (this._coordsTopLeft != null &&
                          this._coordsBottomRight != null)
                        PolygonLayerWidget(
                            options: RectangleRegion(LatLngBounds(
                                    this._coordsTopLeft, _coordsBottomRight))
                                .toDrawable(
                          borderColor: Colors.white60,
                          borderStrokeWidth: 3,
                          fillColor: Colors.white.withOpacity(0.3),
                        ))
                    ])),

**Comment by caini1213** [comment]
![image](https://user-images.githubusercontent.com/58871500/197150389-08aaab82-92e8-4b8c-9340-d52c53a8c3e9.png)
![image](https://user-images.githubusercontent.com/58871500/197150459-4ff30347-1db5-40ab-a935-ee7c37d8d597.png)
![image](https://user-images.githubusercontent.com/58871500/197150499-3059265e-c270-4952-983d-861368b80f93.png)

**Comment by caini1213** [comment]
yes, is unusual... pls let me know if there is any mistake :)  

FYI, 
I pass 
TileLayerOptions(
  maxZoom: 20,
  urlTemplate:
  'http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}')

 when download the region.

**Comment by JaffaKetchup** [comment]
Unfortunately, I can't see any mistakes. It does appear that the function is returning true for all tiles. Can you assure us that those tiles actually aren't downloaded? I cannot see why that function would be broken when working in the example app.

**Comment by JaffaKetchup** [comment]
Can you try painting that polygon for the area you think you downloaded?

**Comment by caini1213** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/58871500/197153495-fe96382c-11f4-4d40-9d73-9033bdbda0ae.png)
 As example, i choose to download the region around these 5 blocks and so, the color region should show around them only.

**Comment by caini1213** [comment]
https://user-images.githubusercontent.com/58871500/197153865-123a6de7-9bcd-45d0-982a-cf10990d02b8.mp4

But it cover all over the map as shown in the video, hmm it's weird

**Comment by JaffaKetchup** [comment]
Ok, another debugging method. Can you try zooming out significantly for me, then zooming in significantly for me - outside the intended downloading area. Can you do a screen recording of that?

**Comment by caini1213** [comment]
https://user-images.githubusercontent.com/58871500/197155248-69320c15-6a5d-43a4-b290-e7524fcb0940.mp4

Like this?

**Comment by JaffaKetchup** [comment]
Ok, that doesn't seem right either. I'll have to investigate, but I'm not sure I'll find anything. I'll be in contact soon. Thanks for your help.

**Comment by caini1213** [comment]
Alright, thank you very much!

**Comment by caini1213** [comment]
Hi there, any updates? :)

**Comment by JaffaKetchup** [comment]
Sorry @caini1213, I haven't had the chance to give it a good look, but as far as I can see, it should be working fine.

If you want to diagnose it on your system in a way that I can't, here's a screenshot of the internals:
![image](https://user-images.githubusercontent.com/58115698/198030742-eb184eac-a66c-4902-a048-2b0f6c59bb46.png)
Try breaking it down and making each value is as you expect.

**Comment by JaffaKetchup** [comment]
Hi @caini1213, did you get any interesting information by using the debug method I proposed above? No problem at all if you've been busy!

**Comment by caini1213** [comment]
Hi @JaffaKetchup, we had found out where is the problem. When there is internet and the downloaded map is loaded, it will auto cached all the new tiles which then save in the store. This is the reason why the red region cover all over the map. So, load the downloaded map only when offline to prevent auto cache will fix the problem!

**Comment by JaffaKetchup** [comment]
@caini1213 Ah I see. You can use the `CacheBehavior.cacheOnly` to do this. Thanks for updating me!
