### ISSUE TITLE
[FEATURE] Add method to catch tile retrieval error

### ISSUE THREAD

**Issue by ozzy1873** [JaffaKetchup/flutter_map_tile_caching#74]
### What is the bug?

I sometimes see this error in Crashlytics. I have added exception handling, but the error somehow still slips through to Crashlytics. What is the proper way to catch this, so it is not reported to Crashlytics?

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: FMTCBrowsingError: Failed to load the tile from the cache or the network because it was missing from the cache and the server responded with a HTTP code other than 200 OK.. Error thrown Instance of 'ErrorDescription'.
       at FMTCImageProvider._loadAsync.finish(image_provider.dart:106)
       at FMTCImageProvider._loadAsync(image_provider.dart:166)

### What is the expected behaviour?

I think the error is expected, but I should be able to catch it, so it is not reported to Crashlytics. I am using the errorTileCallback on the TileLayer:

```
                tileBuilder:
                    (BuildContext context, Widget tileWidget, Tile tile) {
                  if (tile.loadError) {
                    // apply red colorFilter or wrap widget with another custom Widget
                    return Container(color: AppColors.mapBadTile);
                  }
                  return ColorFiltered(
                      colorFilter: notifier.isMapDarkModeEnabled
                          ? MapUtils.colorFilterDark
                          : MapUtils.colorFilterNone,
                      child: tileWidget);
                },
                evictErrorTileStrategy: EvictErrorTileStrategy.dispose,
                errorTileCallback: (Tile tile, error) {
                  if (error != null) {
                    debugPrint(error.toString());
                  }
                },
```

### How can we reproduce this issue?

```dart
Seems to happen sometimes when there is no internet connection, but I do not know how to reliably force the error.
```

### Platforms Affected

Android

### Severity

Minimum: Allows normal functioning

### Frequency

Rarely: Occurs every so often

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map_tile_caching) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @ozzy1873. This error can be safely ignored (I think you can silence/mute in Crashylitics), as it's simply what it says on the tin.
However, you are correct in that there should be a way to catch it. Does the `errorTileBuilder` work correctly?

**Comment by JaffaKetchup** [comment]
This will be fixed by v7 (https://github.com/JaffaKetchup/flutter_map_tile_caching/pull/78).
