### ISSUE TITLE
[BUG] 'flutter_background' blocking build

### ISSUE THREAD

**Issue by andreystavitsky** [JaffaKetchup/flutter_map_tile_caching#77]
### What is the bug?

Due to outdated gradle version in currentrly published flutter_background plugin, this plugin cannot be built.
There's an [issue ](https://github.com/JulianAssmann/flutter_background/issues/65)for this.

That was fixed in [fcce0d57525802b6f720dee0a080a10a0feaca4b](https://github.com/JulianAssmann/flutter_background/commit/fcce0d57525802b6f720dee0a080a10a0feaca4b), but published version of that plugin does not contain this commit.

`   > Could not resolve com.google.jimfs:jimfs:1.1.
     Required by:
         project :flutter_background > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdklib:26.5.0 > com.android.tools:repository:26.5.0
      > Could not resolve com.google.jimfs:jimfs:1.1.
         > Could not get resource 'https://jcenter.bintray.com/com/google/jimfs/jimfs/1.1/jimfs-1.1.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/google/jimfs/jimfs/1.1/jimfs-1.1.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.5.1/userguide/build_environment.html#gradle_system_properties
                  > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed`

### What is the expected behaviour?

Build successful

### Platforms Affected

Android

### Severity

Fatal: Causes the application to crash

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map_tile_caching) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by stx** [comment]
Critical breaking issue for our apps. Trigger is because jcenter's SSL cert expired:

![image](https://user-images.githubusercontent.com/1284134/204074503-11243c13-af3e-4163-b7b5-c0d94ea3a671.png)

**Comment by JaffaKetchup** [comment]
Hey @andreystavitsky, and thanks for letting me know.

For now, you may be able to use a dependency override in your pubspec.yaml. To depend on a git commit, see https://dart.dev/tools/pub/dependencies#git-packages. To override a dependency, see https://dart.dev/tools/pub/dependencies#dependency-overrides.

I won't be able to fix this in this project until a published version is released (I've pinged the author of the package in the issue you linked), because pub.dev packages cannot depend on packages from Git.

Please try this and let me know how it works out!

**Comment by andreystavitsky** [comment]
Hello @JaffaKetchup 
with dependency override build works

> dependency_overrides: 
  flutter_background:
    git:
      url: "https://github.com/JulianAssmann/flutter_background.git"

**Comment by JaffaKetchup** [comment]
That's what I hoped @andreystavitsky :)
Please use this for the time being.

**Comment by JaffaKetchup** [comment]
@stx @andreystavitsky With v7 release fast approaching, I'd like to ask a question. Do you think it would be more appropriate to have a seperate package providing the background download functionality?

**Pros:**
- Easier to setup this package
- Fewer dependencies in this package
- Background downloading is only supported on Android and has very few users (I would imagine) anyway, so seperating would make platform support clearer

**Cons**
- More effort to setup background downloading
- _Can you think of any others?_

**Comment by andreystavitsky** [comment]
@JaffaKetchup my vote is for separate package

**Comment by JaffaKetchup** [comment]
And the same for the import/export functionality, or is that too far?

Happy new years to both of you as well :)

**Comment by andreystavitsky** [comment]
> And the same for the import/export functionality, or is that too far?
> 
I think that main purpose of this plugin is caching, and as for me, I currently needed caching only. Import\export and background downloading, for the other hand, look more suitable for each other. It's my personal opinion, of course.

**Comment by stx** [comment]
@JaffaKetchup Intuitively, when I saw this package I was surprised when I read about background downloading. I think almost everyone looking for this package is just looking for your typical caching (make network request, save it and reuse it.)

I think background downloading and loading is a specific, heavy enough load to justify its own package.

Hope that helps!

**Comment by JaffaKetchup** [comment]
Thanks guys :) I think I'm going to seperate both import/export and background bulk download (I'll leave bulk download in base, as it doesn't add any dependencies) into their own seperate packages.

**Comment by aytunch** [comment]
I agree with the general consensus. This plugin should concentrate on caching and import/export/bg_download can be handled separately.

**Comment by JaffaKetchup** [comment]
@stx Can you change your override to point to the new version on pub.dev?

**Comment by andreystavitsky** [comment]
@JaffaKetchup I can confirm that with 1.2.0 my application was successfully built.
