### ISSUE TITLE
More region selection options

### ISSUE THREAD

**Issue by danielocampo2** [JaffaKetchup/flutter_map_tile_caching#8]
**Describe the solution you'd like**
Cache tiles for a specific area given map center and radius in kilometers.

**Is your feature request related to a problem? Please describe.**
I am trying to apply some caching to a map so it would not have to load all the tiles, let's say, for a specific small city. The goal is to have the map pre-cached for an area of around 10km.

**Describe alternatives you've considered**
So far what I have thought of doing was to get the 4 corners of the current area and cache tiles surrounding those NW, SE, SW and SW points but it seems like too much work and error prone for something it seems to me it would be a very common use case.

Is there any better way of achieving this with the current state of the plugin? Am I missing something?

Thanks a lot for the plugin and all the good work.

**Comment by JaffaKetchup** [comment]
Sound's like a good idea. I'll do some moving around of update planning to make it more realistic (I've got some exams coming up). This will be v3 which now has a due date, and some of the more difficult things will be moved to v4.

**Comment by danielocampo2** [comment]
@JaffaKetchup thanks for the quick response, looking forward to v3.

In the meantime, do you reckon there's a way I can achieve this, at least for a smaller area? While doing some testing, an area of around 1km at only 1 zoom level seems to reach the 20k limit, does that make any sense?
Do you have any recommendation as to how could we precache this before map usage?

Thanks!

**Comment by JaffaKetchup** [comment]
That doesn't seem to be right? Maybe a bug, but I'm not sure, depends which zoom level you're at.
I guess the quick way to do it would be to do some maths using the [second table on this page](https://wiki.openstreetmap.org/wiki/Zoom_levels) and get the coords in each 90° direction and construct a square. I need to do lots of research to come up with a proper solution for a circle, instead of one that doesn't even achieve it's aim!

**Comment by danielocampo2** [comment]
Thanks, it seems that I was doing wrong the calculations. For a ~10km radius area and 3 zoom levels (15-18) it is actually around 20k tiles.

Thanks for your help, will wait until something like this is implemented!

**Comment by JaffaKetchup** [comment]
Great to hear! For some help, could you comment the code you used so I can use it? Thanks.

**Comment by danielocampo2** [comment]
We are actually not going to implement it for now as it was a bit overkill for our app. To test it I just used mocked lat/lon so can't help you much with that.
I was using the formula in the following SO answer but I believe it's not correct: https://stackoverflow.com/a/40500652/5340219

But maybe it helps a little.

**Comment by JaffaKetchup** [comment]
Thanks anyways!

**Comment by JaffaKetchup** [comment]
You can see how I'm getting along in the more-regions branch. Please note, this is not production ready, and is still in development.

**Comment by JaffaKetchup** [comment]
Some progress has been made, please check the branch. I estimate I'm about 1/3 complete?

**Comment by JaffaKetchup** [comment]
Coming soon!

**Comment by danielocampo2** [comment]
Awesome, thanks!

**Comment by JaffaKetchup** [comment]
Sure, no problem!

**Comment by JaffaKetchup** [comment]
https://github.com/JaffaKetchup/flutter_map_tile_caching/pull/11#issuecomment-872529909
