### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sikandernoori** [JaffaKetchup/flutter_map_tile_caching#80]
### What is the bug?

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Exception: No value provided for variable id

### What is the expected behaviour?

It should download the tiles from mapbox server.

### How can we reproduce this issue?

```dart
I am suing example app, the only change I did is I am suing mapbox instead of openstreet.

Endpoint: https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}

Also passing additional options in TileLayer under FlutterMap children[].

 additionalOptions: {
                      'accessToken': model.mapToken,
                      'id': satelliteMode ? model.mapStyleSatellite : model.mapStyleStreets,
                      },
```

### Platforms Affected

iOS

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map_tile_caching) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @sikandernoori,
I'm having trouble believing that this is my library.
In the example app, you can use stores with custom URLs without changing the code. Can you try adding this URL and 'hardcoding' the `id` and API key?
Also, make sure that the ID property in the `additionalOptions` cannot be null.
Thanks for reporting!

**Comment by sikandernoori** [comment]
Checked again on example app and it worked fine.
Something I believe I was doing wrong.

Thanks for quick response.
