### ISSUE TITLE
FMTC storename error

### ISSUE THREAD

**Issue by waleedsyal123** [JaffaKetchup/flutter_map_tile_caching#82]
### What is the bug?

I am unable to find any information about FMTC.instance parameter storename

Here is the error that i am getting:
`[StoreDirectory(rootDirectory: RootDirectory(_rootDirectory: Directory: '/data/user/0/co.appname/app_flutter/fmtc'), storeName: storeName), StoreDirectory(rootDirectory: RootDirectory(_rootDirectory: Directory: '/data/user/0/co.appname/app_flutter/fmtc'), storeName: openstreetmap)]`

Even if run example app, there are no stores to download from, the list is empty
![Screenshot_1673631023](https://user-images.githubusercontent.com/93573575/212382996-66fb7acf-29b7-4610-aba6-faac874499f5.png)

Please explain me from where i can get this storename. right now i have followed everything from your given documentation. I am looking forward for your response.

### What is the expected behaviour?

Right now the application is not saving the tiles, which it should. and there is no explanation about the above parameter.

### How can we reproduce this issue?

```dart
Right now i am using 
- flutter_map: ^3.0.0
- flutter_map_tile_caching: ^6.2.0

Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2486], locale en-US)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)

And with this configuration your example application is having some problems
```

### Can you provide any other information?

Please let me know if you need anything else from my side

### Platforms Affected

Android, iOS

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map_tile_caching) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Hey @waleedsyal123,
Have you created a store in the Stores tab?

**Comment by waleedsyal123** [comment]
Thanks for the help. I couldn't find help regarding this parameter. 👍

**Comment by JaffaKetchup** [comment]
@waleedsyal123 The example app isn't documented, it is designed to be self-explanatory.
I was wondering if you were using this to develop a proprietary application? If so, please see https://fmtc.jaffaketchup.dev/#proprietary-licensing.
