### ISSUE TITLE
[BUG] Fatal memory issues when downloading large number of tiles

### ISSUE THREAD

**Issue by sikandernoori** [JaffaKetchup/flutter_map_tile_caching#86]
### What is the bug?

When I calculate tiles to check how many tiles for a specific region with zoom range from 1 to 21 then I get below error on IOS.

```
* thread #34, name = 'DartWorker', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=3072 MB, unused=0x0)
    frame #0: 0x0000000103dde4c0 Flutter`dart::BlockStack<64>::PopEmptyBlock() + 116
Flutter`dart::BlockStack<64>::PopEmptyBlock:
->  0x103dde4c0 <+116>: stp    q0, q0, [x0, #0x10]
    0x103dde4c4 <+120>: stp    q0, q0, [x0, #0x30]
    0x103dde4c8 <+124>: stp    q0, q0, [x0, #0x50]
    0x103dde4cc <+128>: stp    q0, q0, [x0, #0x70]
Target 0: (Runner) stopped.
Lost connection to device.
```

### What is the expected behaviour?

It should give tiles count.

### How can we reproduce this issue?

```dart
Use countties function from example. and select a large region and zoom level from 1 to 21.i.e

  Future<void> _countTiles() async {
    final DownloadProvider provider = Provider.of<DownloadProvider>(context, listen: false);

    if(provider.region != null)
      provider
        ..regionTiles = null
        ..regionTiles = await FMTC.instance('').download.check(
              provider.region.toDownloadable(
                provider.minZoom,
                provider.maxZoom,
                TileLayer(),
              )
          );

  }
```

### Do you have a potential solution?

Not yet

### Platforms Affected

iOS

### Severity

Fatal: Causes the application to crash

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map_tile_caching) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @sikandernoori,

This looks like an out of memory exception.

Can you confirm you're on the latest version 6.1.0 at the moment, and specify what type of region you are trying to download.

This shouldn't happen with smaller ranges or areas.

I may need to check if there's a leak.

Thanks for the report!

**Comment by sikandernoori** [comment]
It happens only on large areas with zoom level from 1 to 21.

**Comment by sikandernoori** [comment]
I am on older version, but I've tested and the behaviour is same on 6.1.0.

**Comment by JaffaKetchup** [comment]
My apologies @sikandernoori, I've lost track of my own versioning :D

v6.1 isn't the latest and doesn't include the update I was thinking about. Can you double check on v6.2 for me? Again, my apologies.

**Comment by sikandernoori** [comment]
Tested the latest version too, I see you have optimized function by removing for loop and used List generator but issue remains the same, OutOfMemory geths thrown on large area.

**Comment by JaffaKetchup** [comment]
Thanks @sikandernoori, I'm resolving this now for v7. I didn't realise how memory innefficient long lists of numbers could be, so I'll have to switch to a streaming based solution.

![image](https://user-images.githubusercontent.com/58115698/215263739-45c5bdb4-db85-4ff7-97e8-808afa098a0e.png)

**Comment by sikandernoori** [comment]
@JaffaKetchup when are you planning to create v7 release with this bug handled ?

**Comment by JaffaKetchup** [comment]
@sikandernoori I must release it before Sunday 12th, although it will probably be before that anyway.
Unfortunatley, this might be difficult to resolve. I've tried a Stream based implementation, but it hasn't worked. I've opened an SO question: https://stackoverflow.com/q/75268119/11846040. If there are no good answers in two days, I'll put a bounty on it, as I want this resolved ASAP as well.
In the meantime, I've updated my comment above (https://github.com/JaffaKetchup/flutter_map_tile_caching/issues/86#issuecomment-1405217996) with a workaround. Also note that zoom level 21 is way too zoomed in for most use cases - but that doesn't mean this issue isn't high priority, of course.

On a seperate note, are you using FMTC within a proprietary application? If so, please read https://fmtc.jaffaketchup.dev/#proprietary-licensing.

**Comment by sikandernoori** [comment]
For checking Tiles count we can refactor `rectangleTiles` to `rectangleTilesCount` as below, I've tested and it's very fast can be optimized further by removing the zoom level loop too.


```
num rectangleTilesCount(Map<String, dynamic> input) {
  final LatLngBounds bounds = input['bounds'];
  final int minZoom = input['minZoom'];
  final int maxZoom = input['maxZoom'];
  final Crs crs = input['crs'];
  final CustomPoint<num> tileSize = input['tileSize'];

  num tilesCount = 0;
  for (int zoomLvl = minZoom; zoomLvl <= maxZoom; zoomLvl++) {
    final CustomPoint<num> nwCustomPoint = crs
        .latLngToPoint(bounds.northWest, zoomLvl.toDouble())
        .unscaleBy(tileSize)
        .floor();
    final CustomPoint<num> seCustomPoint = crs
            .latLngToPoint(bounds.southEast, zoomLvl.toDouble())
            .unscaleBy(tileSize)
            .ceil() -
        const CustomPoint(1, 1);

    tilesCount += (seCustomPoint.x - nwCustomPoint.x + 1) *
        (seCustomPoint.y - nwCustomPoint.y + 1);
  }
  return tilesCount;
}
```

The problem will rise again though when we start downloading and we need `List<Coords<num>>`, for that I am thinking of writing records in chunks to local storage instead of keeping them in heap. But then I will have to update `_startDownload` function too, to fetch `List<Coords<num>>` from local storage and update progress accordingly, not an efficient way but seems like heap will always be a problem regardless what data structure we use.

**Comment by JaffaKetchup** [comment]
Indeed, the first version of FMTC had a shortcut like that for counting tiles, but it doesn't really solve the issue, because, as you mentioned, it won't help for downloading. Additionally, that maths becomes very hard to do for the circle and line regions.
I'll have to find a solution somehow. Maybe if nothing else works, I'll have to use another database file to store the tiles on disk instead of memory, as you suggested, but that's slow and a hassle, and I'd rather avoid that.

If you are using FMTC within a proprietary application, no problem at all, but please do get in touch :).

**Comment by sikandernoori** [comment]
okay, I will check with team the status of app we are working on and will be in touch.

**Comment by JaffaKetchup** [comment]
@sikandernoori Unfortunatley, it looks like this won't be an easy fix. I've put a bounty on https://stackoverflow.com/q/75268119/11846040 to try to get it answered, but it's looking like it may take a long time, or never. I have to publish v7 this weekend, so I may have to delay this for the next version.
