### ISSUE TITLE
[BUG] Cancelling download on large number of tiles crashes the app

### ISSUE THREAD

**Issue by sikandernoori** [JaffaKetchup/flutter_map_tile_caching#90]
### What is the bug?

Upon cancelling download for large number of tiles crashes the app.

```
../../third_party/dart/runtime/platform/allocation.cc: 22: error: Out of memory.
version=2.19.0 (stable) (Mon Jan 23 11:29:09 2023 -0800) on "ios_arm64"
pid=6385, thread=65851, isolate_group=main(0x12c076000), isolate=(nil)(0x0)
os=ios, arch=arm64, comp=no, sim=no
isolate_instructions=105a74000, vm_instructions=105a74000
  pc 0x0000000106438dcc fp 0x00000001706fa080 Dart_DumpNativeStackTrace+0x18
  pc 0x000000010600af3c fp 0x00000001706fa0a0 dart::Assert::Fail(char const*, ...) const+0x30
  pc 0x00000001062316d4 fp 0x00000001706fa0d0 dart::BlockStack<64>::PopNonEmptyBlock()+0x0
  pc 0x0000000106227ef4 fp 0x00000001706fa120 dart::MarkingVisitorBase<true>::VisitPointers(dart::ObjectPtr*, dart::ObjectPtr*)+0x130
  pc 0x0000000106166728 fp 0x00000001706fa170 dart::UntaggedObject::VisitPointersPredefined(dart::ObjectPointerVisitor*, long)+0x374
  pc 0x00000001062277a8 fp 0x00000001706fa1d0 dart::MarkingVisitorBase<true>::ProcessMarkingStack(long)+0x360
  pc 0x0000000106227220 fp 0x00000001706fa650 dart::ConcurrentMarkTask::Run()+0x134
  pc 0x00000001061fa900 fp 0x00000001706fab50 dart::ThreadPool::Worker::Main(unsigned long)+0x18c
  pc 0x0000000106157fd8 fp 0x00000001706fafc0 dart::ThreadStart(void*)+0x120
  pc 0x00000002208b66cc fp 0x00000001706fafe0 _pthread_start+0x94
-- End of DumpStackTrace
* thread #48, name = 'DartWorker', stop reason = signal SIGABRT
    frame #0: 0x000000021019f160 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x21019f160 <+8>:  b.lo   0x21019f180               ; <+40>
    0x21019f164 <+12>: pacibsp
    0x21019f168 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x21019f16c <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.
```

### What is the expected behaviour?

It  should clear the download queue and clear memory.

### How can we reproduce this issue?

```dart
Select large area with more than 3.3 million tiles and start download, then cancel the download and app will crash.
```

### Do you have a potential solution?

Not yet, WIP.

### Platforms Affected

iOS

### Severity

Fatal: Causes the application to crash

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map_tile_caching) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
@sikandernoori Thanks for the report :)

I wouldn't try to download 3.3 million worth of tiles if I were you (thats unreasonable in terms of time and space), but I appriciate that that's not a great excuse.

This may take a while to solve and may involve me having to find a custom parallel queue solution, which may also help with #86.
But for now, I'm taking a **short** break from FMTC (there may be an update this weekend) to focus on rebuilding my own website and some other personal matters. Don't worry, this won't be neglected in any way, and I'll still be responding to feedback and implementing critical fixes. For now, this is low priority.

**Comment by JaffaKetchup** [comment]
This appears as though it might be related to #68. If so, fix will arrive in v8.
