### ISSUE TITLE
[BUG] Migrator runs directory delete operation even if directory doesn't exist

### ISSUE THREAD

**Issue by LPETERS006** [JaffaKetchup/flutter_map_tile_caching#97]
### What is the bug?

![image](https://user-images.githubusercontent.com/26815219/219075590-51288450-5af7-424b-8f7c-12f414e6623b.png)
Thats all i got.

### What is the expected behaviour?

Something that shows me that versions higher than 6.2.0 work. Because i have a lot of problems with higher versions....😉

### How can we reproduce this issue?

Maybe you try installing on latest win11?!

### Do you have a potential solution?

No

### Can you provide any other information?

No

### Platforms Affected

Windows

### Severity

Minimum: Allows normal functioning

### Frequency

Once: Occurred on a single occasion

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] I have checked for known issues in the GitHub tracker and [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#known-issues)
- [X] I have completed the pre-report checks listed [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#reporting-a-bug)
- [X] If I am using FMTC in a proprietary project, I have read and understood [this important legal notice](https://fmtc.jaffaketchup.dev/#proprietary-licensing)

**Comment by LPETERS006** [comment]
First of all, I am really pleasantly surprised by your quick response. Thank you. I'll try it out tomorrow morning and report back how it worked.

**Comment by JaffaKetchup** [comment]
Sure, no problem.

**Comment by JaffaKetchup** [comment]
Hey @LPETERS006, just checking to see if you've managed to get the app launching?

**Comment by LPETERS006** [comment]
Sorry, I had a lot to do yesterday and didn't get around to testing. But I just tested it now and I think I finally found the problem. I even guess it is/was the same problem on Android that I had. It seems that the Store folder is not created at the first start. Here is the debug output (Windows)...

>  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Deletion failed, path = 'C:\Users\Petersen\Documents\fmtc\stores' (OS Error: Das System kann den angegebenen Pfad nicht finden.
> 
> , errno = 3)
> #0      _checkForErrorResponse (dart:io/common.dart:55:9)
> #1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:185:7)
> <asynchronous suspension>
> #2      RootMigrator.fromV6 (package:flutter_map_tile_caching/src/root/migrator.dart:200:29)
> <asynchronous suspension>
> #3      main (package:fmtc_example/main.dart:32:3)
> <asynchronous suspension>

**Comment by LPETERS006** [comment]
....Even though the error here says that it cannot delete the folder.... but it is not created either.

**Comment by JaffaKetchup** [comment]
@LPETERS006 This is part of the v6 -> v7 migration code I think, as v7 doesn't use directories and files anymore. For now, you can just comment out the line in main.dart that ends with `fromV6();`, and it should work.
I thought I put safeguards in place to prevent the migration system from running unnecessarily, and I can't reproduce this myself. Did you delete the FMTC directory before running? If you didn't, what did it contain?

**Comment by LPETERS006** [comment]
👍 Then I'm already getting closer to the matter. I'll get back to you with my other problem sometime in the next few days. I still have to collect debug data. 
In advance... Under 6.8 I can retrieve several layers from my own geoserver and overlay them on the map. And that works really well. In my first 7.x tests I could only use osm and as soon as the wms layers were active a grey screen appeared... As I said, I'm collecting error messages and will report back when I've narrowed down the problem a bit. 

Thanks again for the fast support.

![image](https://user-images.githubusercontent.com/26815219/219602380-7dfdac35-e38d-489d-b879-8086e4654d30.png)

**Comment by JaffaKetchup** [comment]
Thanks, error reports do help! I'll have a little spare time this weekend to try and fix this :)

**Comment by JaffaKetchup** [comment]
Hey @LPETERS006,
Please open a new issue with more information about the WMS information, if you can as soon as possible. I've also run into this issue in another project, and am trying to debug it myself, but am finding it difficult.
I've opened a PR that should fix the migrator bug - although there was protection in place before, I've added another check directly before the delete operation.

**Comment by JaffaKetchup** [comment]
I think the second issue you mentioned may have been fixed also by v7.1.2. Please double check!
