### ISSUE TITLE
[BUG] Schema mismatch

### ISSUE THREAD

**Issue by unexus** [JaffaKetchup/flutter_map_tile_caching#99]
### What is the bug?

Hi

Isar throws errors if we set the "maxStoreLength" parameter in "FMTCTileProviderSettings".

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: IsarError: SchemaMismatch: The schema of the existing instance does not match.
#0      nCall (package:isar/src/native/isar_core.dart:174:5)
#1      openIsarSync.<anonymous closure> (package:isar/src/native/open.dart:141:5)
#2      using (package:ffi/src/arena.dart:124:31)
#3      openIsarSync (package:isar/src/native/open.dart:129:10)
#4      Isar.openSync (package:isar/src/isar.dart:137:12)
#5      _removeOldestTile (package:flutter_map_tile_caching/src/providers/image_provider.dart:243:19)
#6      compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:18:20)
#7      _RemoteRunner._run (dart:isolate:954:47)

```

File "image_provider.dart" line 244:
```
Future<void> _removeOldestTile(List<Object> args) async {
  final db = Isar.openSync(
    [DbTileSchema, DbMetadataSchema],
    name: DatabaseTools.hash(args[0] as String).toString(),
    inspector: false,
  );
```

### What is the expected behaviour?

no errors while checking for obsolete maptiles

### How can we reproduce this issue?

Set parameter "maxStoreLength" parameter in "FMTCTileProviderSettings" and move the map

### Do you have a potential solution?

Adding "DbStoreDescriptorSchema" to the schemalist worked for us:

```
Future<void> _removeOldestTile(List<Object> args) async {
  final db = Isar.openSync(
    [DbTileSchema, DbMetadataSchema, DbStoreDescriptorSchema],
    name: DatabaseTools.hash(args[0] as String).toString(),
    inspector: false,
  );
```

### Can you provide any other information?

 isar: ^3.0.5
 isar_flutter_libs: ^3.0.5
 flutter_map_tile_caching: ^7.1.1
 flutter_map: ^3.1.0

### Platforms Affected

Android, iOS

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

### Frequency

Often: Occurs more often than when it doesn't

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] I have checked for known issues in the GitHub tracker and [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#known-issues)
- [X] I have completed the pre-report checks listed [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#reporting-a-bug)
- [X] If I am using FMTC in a proprietary project, I have read and understood [this important legal notice](https://fmtc.jaffaketchup.dev/#proprietary-licensing)

**Comment by JaffaKetchup** [comment]
Hi @unexus, and thanks for this report. Indeed, this is a bug. I'll try to resolve it this weekend.
